### ISSUE TITLE
[feature]: SEO optimization for UPWARD with react-ssr

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#1110]
**Is your feature request related to a problem? Please describe.**
Our current solution for SSR is flexible for UPWARD but can be improved with recent updates to react-ssr and other proposals as mentioned in #510. SSR is achieved using mustache templates in UPWARD.

**Describe the solution you'd like**
Adding an option for react-ssr to UPWARD (configurable) gives us an option for simple SSR but leaves the flexibility of templates defined initially in the protocol. Efforts would include:

- Adding a `react` template engine to the `upward-js` TemplateResolver
- Reviewing and adjusting Venia code to render full pages in react-html, without a browser DOM
- Dockerizing upward-js with react-html support and providing a ready-made Docker image for an UPWARD server
- _Nice to have:_ Writing the React template engine as a separate service or process for maximal compatibility with upward-php and other implementations 

**Describe alternatives you've considered**
Current approach for SSR is viable, but prioritizes portability and server stack independence over simplicity of code. Either SSR is limited to the metadata and app shell, or the project must have code duplication in React components and templates.

**Additional context**
Research needed to create POC, test and optimize these improvements to UPWARD which may require additional issues for grooming.

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [X] `upward-js`
- [X] `upward-spec`

**Comment by paales** [comment]
Wanted to comment on this as we've been burned very heavily in the past when relying on client side rendering only and we've came to the conclusion that proper SSR is absolutely required.

In the end, even though Google can render pages with their render engines, their html-scraper is x-amounts of time as fast, which reflects in the ranking of a page.

And besides that, 'pre rendering' on the server allows for faster initial paint because the server is able to determine critical css, the rendered dom, etc.

And in a few months React comes out with their new SSR Streaming server tech that they are building for the new Facebook 5 launch. This will make the SSR option even more viable.

I've been trying to get NextJS as an operating backend for the frontend, but ran into issues that the venia-ui theme currently still relies on client side API's and need to be refactored or they need to be moved to a client side only renderer (which nextjs can do fairly easily).

**Comment by disvroian** [comment]
Hello;
Is there any follow up on this?
Or any solution good to use to do SEO?

**Comment by BioSehnsucht** [comment]
This was just released but I'm unclear on how to use it with PWA (they have a flowchart but it doesn't show how/where it would actually connect to PWA, etc)

https://seosnap.io/ / https://github.com/experius/SeoSnap

I would prefer something that didn't require quite so much extra baggage to implement, myself.

**Comment by awilcoxa** [comment]
Addressing with extensibility framework/POC from @zetlen, closing this issue for now and will follow up with additional issues/stories

**Comment by paales** [comment]
@awilcoxa Can you link this issue in the replacement issues/stories?

**Comment by paales** [comment]
@awilcoxa Not wanting to get this forgotten, are followup tickets created?

**Comment by davemacaulay** [comment]
@ericerway can we share more information with @paales regarding his questions?

**Comment by beHitesh** [comment]
Hi, Do we have any documentation or implementation examples for SSR support? It would be really helpful- thank you.

**Comment by levygrunwald** [comment]
@paales was there ever a follow up on this. I feel strongly about the benefits of SSR for optimized first contentful paint. Was also considering next.js.

Also wondering on your person solution to this outside of the official framework.

**Comment by paales** [comment]
Last I've heard, they are not planning on implementing SSR. We're developing our own frontend stack because of this and because of: lack of typescript support, lack of graphql code gen support (typescript related), wrong abstractions on the extensibility framework (creating webpack overrides), lack of first class support of other cms'es (can't blame them for this, but still a consideration for us).

**Comment by jimbo** [comment]
> @paales was there ever a follow up on this. I feel strongly about the benefits of SSR for optimized first contentful paint. Was also considering next.js.

Yes, we're aiming to implement Node-based SSR this year; that epic is on our roadmap now and we'll hopefully begin next quarter. As part of that work, we'll determine how SSR and Upward fit together. And when that time comes, we'd always welcome another pair of eyes. 🙂

**Comment by sm1thana** [comment]
@jimbo Hi!
Is there any success in determination of fitting SSR and Upward?

**Comment by maxbmx** [comment]
Hi, how things are going with SSR? :-)

**Comment by davibennun** [comment]
Any updates on this?
