### ISSUE TITLE
[feature]: Implement quantity dropdown as increment decrements with text-box on PDP

### ISSUE THREAD

**Issue by narendravyas24** [magento/pwa-studio#1281]
**Description:**
As currently on PDP and on product-edit a dropdown is provided for "Quantity" in venia theme. That doesn't seems to be good from a user point of view. 

So instead of dropdown we may prefer going with an increment-decrement (+/-) with a text-box as well. So that user may simply increase/decrease value as per the need or may provide any quantity inside the text-box of quantity.

![imageedit_2_6918117914](https://user-images.githubusercontent.com/47310514/58625656-87959580-82f0-11e9-9997-c083e5fa0606.gif)

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## Tracked By

https://jira.corp.magento.com/browse/PWA-119

**Comment by awilcoxa** [comment]
@soumya-ashok

**Comment by soumya-ashok** [comment]
@narendravyas24 Is your opinion that a dropdown is not good from a user point of you based on a desktop or mobile experience?

**Comment by brendanfalkowski** [comment]
I'm working on migrating our "stepper" component from M1 into PWA next week:
https://www.gemaire.com/design/patterns/form/stepper/

We tend to avoid `<select>` whenever possible because it's at minimum two touches (or three if scrolling) to set a value. It also blocks setting a specific value that's not in the options.

The "stepper" provides one touch access for common quantity changes (+ 1,2,3) and allows manually setting a value.

There's also this old gem of a presentation: https://www.fuckdropdowns.com/

**Comment by narendravyas24** [comment]
@soumya-ashok 

In my opinion drop-down is neither good in mobile nor in desktop, there can be various possible reasons for that, as:

1. Dropdown blocks the input of any desired quantity by user that is not specified in the dropdown.

2. Number of clicks/touches are more than one in case of drop-down's than the stepper.

3. Only stepper can also be very annoying to user so I mentioned to use a text-box as well in addition to stepper. In which a user can provide any input as needed.

4. In the current implementation the options of drop-down are also mentioned in (src/components/ProductQuantity/mockData.js). So in case if a client needs to change the option that can done by changing the content of mockData.js, that is also not good.

5. Dropdown seems not feasible if quantities in decimal is allowed. A text-box can work in this case as well.

Using a text-box with a stepper seems to be capable enough to solve all these problems. Let me know your thoughts.

Thanks.

**Comment by soumya-ashok** [comment]
@brendanfalkowski Thanks for sharing those links.
As far as the stepper design is concerned, I'm struggling with the same question as the one @belbiy asked in the PR. Having the increase and decrease buttons on either side of the field seems counter-intuitive.

On the subject of dropdowns, I don't disagree that they contribute to friction in a number of contexts in the shopper flow. However, I don't necessarily see the advantage of replacing it with a stepper for quantities - I think that an open text field with a context-aware numeric keyboard would be significantly better than a dropdown.

Thoughts?

**Comment by soumya-ashok** [comment]
> @soumya-ashok
> 
> In my opinion drop-down is neither good in mobile nor in desktop, there can be various possible reasons for that, as:
> 
> 1. Dropdown blocks the input of any desired quantity by user that is not specified in the dropdown.
In the case of quantity, this is not usually up to the user to decide in a B2C flow. There are only a certain number of options, usually 1-10 that a user can choose from, so I am not sure what you mean by "blocking".
> 2. Number of clicks/touches are more than one in case of drop-down's than the stepper.
Depends on the quantity being chosen - On mobile, a dropdown is a tap, a scroll and another tap regardless of the quantity, but in a stepper the number of taps would vary.
> 3. Only stepper can also be very annoying to user so I mentioned to use a text-box as well in addition to stepper. In which a user can provide any input as needed.
Agreed.
> 4. In the current implementation the options of drop-down are also mentioned in (src/components/ProductQuantity/mockData.js). So in case if a client needs to change the option that can done by changing the content of mockData.js, that is also not good.
> 5. Dropdown seems not feasible if quantities in decimal is allowed. A text-box can work in this case as well.
We do not have decimals in this use case, but if we did, providing an open text input would cover both whole numbers and decimals.
> 
> Using a text-box with a stepper seems to be capable enough to solve all these problems. Let me know your thoughts.

I'd like to ask you the question as in my previous comment. Do we absolutely need a stepper? A text field with a numeric keyboard would cover just about any case and the intent of the UI element would be very clear.

> 
> Thanks.

Thanks for the discussion!

**Comment by brendanfalkowski** [comment]
@soumya-ashok — Replies below :)

> As far as the stepper design is concerned, I'm struggling with the same question as the one @belbiy asked in the PR. Having the increase and decrease buttons on either side of the field seems counter-intuitive.

Replied in the PR comments before I saw this, but I disagree on this one and strongly because we tested it and it changed my mind. I was initially in the right-side buttons camp:

- 2012: https://dribbble.com/shots/745486-Add-To-Cart
- 2013: https://dribbble.com/shots/887571-Angry-Birds-Shop
- 2014 (after testing): https://dribbble.com/shots/1421955-Add-To-Cart

People were faster and more accurate (few mistaps) when the buttons were separated. It gives tighter lockups with the main CTA. Better balance than weighting buttons to one side, and easer to touch since the targets are farther apart.

> On the subject of dropdowns, I agree that they contribute to friction in a number of contexts in the shopper flow. However, I don't necessarily see the advantage of replacing it with a stepper for quantities - I think that an open text field with a context-aware numeric keyboard would be significantly better than a dropdown.

A stepper is the best of both worlds. One-touch access for adjacent quantity changes, and supports typing directly in the input. A dropdown is worse in both cases.

B2C fabric sellers, for example, generally list prices by yard and the user may need 31 yards. A dropdown isn't a good UI for the flexibility this context requires.

**Comment by soumya-ashok** [comment]
> @soumya-ashok — Replies below :)
> 
> > As far as the stepper design is concerned, I'm struggling with the same question as the one @belbiy asked in the PR. Having the increase and decrease buttons on either side of the field seems counter-intuitive.
> 
> Replied in the PR comments before I saw this, but I disagree on this one and strongly because we tested it and it changed my mind. I was initially in the right-side buttons camp:
> 
> * 2012: https://dribbble.com/shots/745486-Add-To-Cart
> * 2013: https://dribbble.com/shots/887571-Angry-Birds-Shop
> * 2014 (after testing): https://dribbble.com/shots/1421955-Add-To-Cart
> 
> People were faster and more accurate (fewer mistaps) when the buttons were separated. It gives tighter lockups with the main CTA. Better balance than weighting buttons to one side, and easer to touch since the targets are farther apart.
> 

I see. Thanks for sharing that.

> > On the subject of dropdowns, I agree that they contribute to friction in a number of contexts in the shopper flow. However, I don't necessarily see the advantage of replacing it with a stepper for quantities - I think that an open text field with a context-aware numeric keyboard would be significantly better than a dropdown.
> 
> A stepper is the best of both worlds. One-touch access for adjacent quantity changes, and supports typing directly in the input. A dropdown is worse in both cases.
> 
> B2C fabric sellers, for example, generally list prices by yard and the user may need 31 yards. A dropdown isn't a good UI for the flexibility this context requires.

No arguments on stepper being better than dropdown for immediate increments, I agree.
So you prefer an open input field in combination with a stepper to only an open input field and no stepper?

**Comment by brendanfalkowski** [comment]
@soumya-ashok — I'm always in the stepper camp now :)

It's just more utility in the same physical space. Some other examples from my projects where/why we've used them:

1. It's more discernable as a UI fixture because it has multiple elements and a fixed width. When some elements get super wide (text and select inputs, buttons) they suffer from decreased pattern recognition. Containing it helps focus/chunk the UI into a smaller area.

<img width="468" alt="Screen Shot 2019-06-11 at 12 52 49 PM" src="https://user-images.githubusercontent.com/214924/59302016-d70c8780-8c47-11e9-9193-76a36817b01d.png">

2. I usually build larger/smaller variants for areas where the UI needs to be denser in lists:

<img width="199" alt="Screen Shot 2019-06-11 at 1 02 22 PM" src="https://user-images.githubusercontent.com/214924/59302624-3dde7080-8c49-11e9-8885-bb0b1e35b87a.png">

<img width="390" alt="Screen Shot 2019-06-11 at 1 05 43 PM" src="https://user-images.githubusercontent.com/214924/59302831-b6ddc800-8c49-11e9-99e3-0be80abf9eeb.png">

3. And even denser variants (including the right-weighted buttons that are oversized for tactile benefit but adjacent for rapid bumping up,up,up,up,down):

<img width="852" alt="Screen Shot 2019-06-11 at 12 47 52 PM" src="https://user-images.githubusercontent.com/214924/59302194-3ff3ff80-8c48-11e9-8929-7d4ba12b1120.png">

Some of these steppers need upper/lower ranges and custom increments (0.5 or 1000), and that's much harder to convey and live-validate in a text input alone.

It's easier for power users to `tap,tap,tap,move,tap,tap,move,tap,tap,tap,tap` that interact with select or text inputs when quantities are stepped over a wide range. Sometimes a range slider is good when an exact input isn't needed (but not the case here).

**Comment by narendravyas24** [comment]
@soumya-ashok 

Regarding the blocking that I mentioned: 
Say in dropdown if the options are (1-10), there is no option for user to buy even more than 10. 

Also there is no option to change the dropdown options, the only solution is to change options from the code.

I think it's always better to add a stepper as well as with the text-box, most of the benefits are mentioned already by @brendanfalkowski . 

Please share your views.

**Comment by soumya-ashok** [comment]
> @soumya-ashok
> 
> Regarding the blocking that I mentioned:
> Say in dropdown if the options are (1-10), there is no option for user to buy even more than 10.
> 
Yes but this not something a stepper can solve. It is entirely the merchant's decision how many they want to make available for a customer to buy based on how they manage inventory.

> Also there is no option to change the dropdown options, the only solution is to change options from the code.
> 
> I think it's always better to add a stepper as well as the text-box, most of the benefits are mentioned already by @brendanfalkowski .
> 
> Please share your views.

In general, we could certainly switch the quantity selector to a stepper component but based on the screenshot, the styling of your stepper component is different than other elements in Venia. I will need to consult with the team here for their feedback before I can get back to you.

Thanks for the work!

**Comment by soumya-ashok** [comment]
> @soumya-ashok — I'm always in the stepper camp now :)
> 
> It's just more utility in the same physical space. Some other examples from my projects where/why we've used them:
> 

Yes, I'd agree with this.

> 1. It's more discernable as a UI fixture because it has multiple elements and a fixed width. When some elements get super wide (text and select inputs, buttons) they suffer from decreased pattern recognition. Containing it helps focus/chunk the UI into a smaller area.
> 
During testing, were you able to observe that shoppers recognized the open field as something they could tap into and modify by typing?

> <img alt="Screen Shot 2019-06-11 at 12 52 49 PM" width="468" src="https://user-images.githubusercontent.com/214924/59302016-d70c8780-8c47-11e9-9193-76a36817b01d.png">
> 
> 1. I usually build larger/smaller variants for areas where the UI needs to be denser in lists:
> 
> <img alt="Screen Shot 2019-06-11 at 1 02 22 PM" width="199" src="https://user-images.githubusercontent.com/214924/59302624-3dde7080-8c49-11e9-8885-bb0b1e35b87a.png">
> 
> <img alt="Screen Shot 2019-06-11 at 1 05 43 PM" width="390" src="https://user-images.githubusercontent.com/214924/59302831-b6ddc800-8c49-11e9-99e3-0be80abf9eeb.png">
> 
> 1. And even denser variants (including the right-weighted buttons that are oversized for tactile benefit but adjacent for rapid bumping up,up,up,up,down):
> 
> <img alt="Screen Shot 2019-06-11 at 12 47 52 PM" width="852" src="https://user-images.githubusercontent.com/214924/59302194-3ff3ff80-8c48-11e9-8929-7d4ba12b1120.png">
> 
> Some of these steppers need upper/lower ranges and custom increments (0.5 or 1000), and that's much harder to convey and live-validate in a text input alone.
> 
> It's easier for power users to `tap,tap,tap,move,tap,tap,move,tap,tap,tap,tap` than interact with select or text inputs when quantities are stepped over a wide range. Sometimes a range slider is good when an exact input isn't needed (but not the case here).

Thanks for all the great examples, and for the feedback! I'll discuss with the team here and figure out how to move forward with this change.

**Comment by brendanfalkowski** [comment]
@soumya-ashok — Per:

> During testing, were you able to observe that shoppers recognized the open field as something they could tap into and modify by typing?

Mind you this was 5 years ago, but I recall the test was a timed exercise like:

- Click provided link
- Add 1 to cart
- Click provided link
- Add 3 to cart
- Click provided link
- Add 25 to cart
- Visit cart
- Change item with 25 to 20
- Change item with 3 to 1

I don't recall anyone tapping (+) 25 times, and we put that in specifically to see if they would try typing— which they did when it was too hard to tap many times.

— — — — — — — — — — 

> It is entirely the merchant's decision how many they want to make available for a customer to buy based on how they manage inventory.

I agree, but this type of constraints should be customization mainly because it's not configurable. The default UI should be open-ended rather than requiring customization to change.

In the Magento admin there's config to limit the quantity in cart for checkout, but I've never seen a store actually limit that. Even so, that blockade happens at checkout (not during add to cart). So you'd always be able to build and price the exact cart you want to see.

In B2B volume discounts are very common and advertised on the PDP as pricing breaks. So it would be very strange to say "buy 50+ and save 4% per unit" but then only allow adding 10 to cart due to the UI element.

The premise of limiting how many can be ordered at once (beyond available stock) just wouldn't make sense to the business. Let people buy it, they'd say.

There is one B2B case that refutes this, which is customers buying for their own warehousing. Sometimes when a manufacturer releases product to distributors, a handful of aggressive customers will buy up 100% of the stock to effectively block their competitors from having a critical component. 

Probably most famous was Apple contracting to buy nearly every 2.5" hard disks from 2001–2006 so no competitors could physically build devices that matched iPods on storage capacity.

It's crazy but it happens in HVAC distributing. We looked at implementing purchase limits on the product level and customer level immediately after replenishment but decided it was simpler to omit showing the specific quantity available globally for contested products. So there was less knowledge of which items could be bought out.

**Comment by soumya-ashok** [comment]
Completely see this for B2B, I was only referring to the Venia use case for a fashion vertical, B2C situation. Based on what I've observed on most retail sites, the most common cap for a single item is 10, and it's usually in a dropdown 😄 

Appreciate the details on the test!

**Comment by narendravyas24** [comment]
@soumya-ashok 

I would still suggest using a stepper and if not stepper at-least even go with a text-box instead. For both B2B and for B2C.

But I have some questions:

1. Yes I have also seen dropdown in some fashion sites but in most of the eCommerce sites I have never seen the dropdown even not in various fashion sites.
 
2. Is it like this that Venia theme is been designed only from a fashion point of view ?

3. I think in any eCommerce it's not even good to restrict the number of selling items (although it depends on merchant but this should not be the default behaviour), even not in B2C. Also in current Magento (without PWA) a dropdown is not preferred.

4. A Merchant can decide to sell the items in any manner as in some products there may be need of dropdown and in some there may be need of stepper/text. We should consider a generalized case that is been preferred in most of the eCommerce websites. 

5. Also the options of dropdown are not dynamic enough, say if only one/two quantity is been left then also dropdown will show all 10 options.

6. How admin/merchant is going to decide the options of dropdown as they are statically defined in the current implementation, is it so that every time in order to change the options we need to perform changes in the static json in file.

> In general, we could certainly switch the quantity selector to a stepper component but based on the screenshot, the styling of your stepper component is different than other elements in Venia. I will need to consult with the team here for their feedback before I can get back to you.
> 
> Thanks for the work!

@soumya-ashok  Please let me know the feedback, I can design here as per your requirements and implement the same here. If finalized you may share some screenshots with which I may take reference and implement the design .

Thanks and please share the views.

**Comment by soumya-ashok** [comment]
> @soumya-ashok
> 
> I would still suggest using a stepper and if not stepper at-least even go with a text-box instead. For both B2B and for B2C.
> 

We are not addressing B2B cases with Venia, only B2C.

> But I have some questions:
> 
> 1. Yes I have also seen dropdown in some fashion sites but in most of the eCommerce sites I have never seen the dropdown even not in various fashion sites.
> 2. Is it like this that Venia theme is been designed only from a fashion point of view ?

Venia is an example or reference theme with the most generic UI elements that feature on an E-commerce site. And yes, this particular example uses a fashion retail vertical because that is what the older version of Venia was based on.

> 3. I think in any eCommerce it's not even good to restrict the number of selling items (although it depends on merchant but this should not be the default behaviour), even not in B2C. Also in current Magento (without PWA) a dropdown is not preferred.

Since any reference theme is customizable by the merchant, they can set or not set limits as they wish.

> 4. A Merchant can decide to sell the items in any manner as in some products there may be need of dropdown and in some there may be need of stepper/text. We should consider a generalized case that is been preferred in most of the eCommerce websites.

The most generic case is to provide an open numeric field with keyboard entry. Whoever wants to add a stepper to their site is welcome to do so. I plan to open a separate issue to convert the quantity dropdown to an open numeric field. If this is a change you would be interested in contributing, please let me know. 

> 5. Also the options of dropdown are not dynamic enough, say if only one/two quantity is been left then also dropdown will show all 10 options.

That should not happen regardless of what UI mechanism is used to select the quantity. Inventory availability should be reflected correctly in the product configuration, but that is outside the scope of this discussion.

> 6. How admin/merchant is going to decide the options of dropdown as they are statically defined in the current implementation, is it so that every time in order to change the options we need to perform changes in the static json in file.
> 
> > In general, we could certainly switch the quantity selector to a stepper component but based on the screenshot, the styling of your stepper component is different than other elements in Venia. I will need to consult with the team here for their feedback before I can get back to you.
> > Thanks for the work!
> 
> @soumya-ashok Please let me know the feedback, I can design here as per your requirements and implement the same here. If finalized you may share some screenshots with which I may take reference and implement the design .
> 
> Thanks and please share the views.

**Comment by narendravyas24** [comment]
> The most generic case is to provide an open numeric field with keyboard entry. Whoever wants to add a stepper to their site is welcome to do so. I plan to open a separate issue to convert the quantity dropdown to an open numeric field. If this is a change you would be interested in contributing, please let me know.

Thanks for that information @soumya-ashok. 
I would like to work on the change as suggested by you, please open the issue for the same and I can work on that. 
Thanks.

**Comment by soumya-ashok** [comment]
I've opened the issue - https://app.zenhub.com/workspaces/pwa-studio-5b23bf79d195c635a1a218ce/issues/magento-research/pwa-studio/1370 - I am still working through some details

**Comment by narendravyas24** [comment]
@soumya-ashok : Thanks, I will work on the same and will perform changes on the PR already raised.

**Comment by sirugh** [comment]
The contributor hasn't commented or updated the PR in a few weeks so I closed it with a comment explaining that.

We're still hoping someone can take this work across the finish line. If you want to do this, let us know! Just branch off the old PR and make the changes requested and we can reopen the PR or open a new one.

Thanks!

**Comment by jonfres** [comment]
Hello, is there someone interested on this issue? Otherwise I'll ask for it.

**Comment by sirugh** [comment]
You've got it @jonfres!

**Comment by supernova-at** [comment]
@jonfres any updates on this one?

**Comment by brendanfalkowski** [comment]
@supernova-at — I implemented this months ago. It wouldn't be much work to migrate this into Venia styling. Assign to me?

@soumya-ashok Can you post the mockup of the layout/coloring you last had okay'ed to implement? I think it got lost in another ticket.

**Comment by sirugh** [comment]
Done. @brendanfalkowski I think Soumya is on PTO for a few days so it might be a while.

**Comment by brendanfalkowski** [comment]
Hi @soumya-ashok, did you have a layout/colorized mockup of the quantity stepper?

I may have some time next week, and it looks like https://github.com/magento/pwa-studio/pull/2094 has a placeholder for this.

**Comment by sirugh** [comment]
@brendanfalkowski we have an internal ticket with mocks, https://jira.corp.magento.com/browse/PWA-119. It looks to me like it's just black/white. Here's some screenshots I took of them that should show the desired alignment on mobile/desktop. Try to control spacing with variations of `1rem`.

**Comment by awilcoxa** [comment]
https://jira.corp.magento.com/browse/PWA-119
