### ISSUE TITLE
[Category Filtering]:Complete Category Filtering Feature w/ GQL 

### ISSUE THREAD

**Issue by awilcoxa** [magento/pwa-studio#1432]
In https://github.com/magento-research/pwa-studio/issues/361 we completed the UI requirements for Category filtering but at the time we were blocked on completion due to GQL dependency. That GQL requirement is now completed and so additional effort is required to connect the UI to the backing GQL endpoint. 

GQL dependency: https://github.com/magento/graphql-ce/pull/259 

**Describe the solution you'd like**
Category Filters are now complete and available in Venia

**Please let us know what packages this feature is in regards to:**
- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [x] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by sirugh** [comment]
@awilcoxa As far as I can tell we are still restricted to filtering products based on this schema: [ProductFilterInput](https://github.com/magento/graphql-ce/blob/dffe94dcd89a02ef3c3a7e5bec28f25346a9a67a/app/code/Magento/CatalogGraphQl/etc/schema.graphqls#L279-L315). If there is another way we are supposed to filter, I'd like to learn about it.

For context, we [currently filter](https://github.com/magento-research/pwa-studio/blob/develop/packages/venia-concept/src/queries/getCategory.graphql#L20) by `category_id`, which is an attribute on `ProductFilterInput`:

```gql
products(
  filter: { category_id: { eq: "11" } }
)
```

Assuming we are wanting to filter using that filter variable, I would expect to be able to expand the object similar to the code below, except that we aren't because the filter object is pre-defined to be the `ProductFilterInput` type.

```gql
products(
  filter: { 
    category_id: { eq: "11" }
    fashion_material: { eq: "39" } # 39 == cotton
  }
)
```

It's also possible I'm not even approaching this the right way so I'm just documenting my findings so far for my own sake :D

**Comment by sirugh** [comment]
Ah, looks like this is related: https://github.com/magento/graphql-ce/issues/500

**Comment by awilcoxa** [comment]
https://devdocs.magento.com/guides/v2.3/rest/performing-searches.html

Needs additional GQL research to determine if we are blocked.

**Comment by zetlen** [comment]
Posted [a comment](https://github.com/magento/graphql-ce/issues/500#issuecomment-516064481) in magento/graphql-ce#500 suggesting an alternate input structure that the GQL team _might_ find it easier to implement. They'd have to weigh in.

**Comment by TomashKhamlai** [comment]
:bell: magento/graphql-ce#500

**Comment by sirugh** [comment]
* Custom attributes will get added to the schema after you flush the config cache.

* ProductAttributeFilterInput on 2.3.4:
    https://i.gyazo.com/869d6bddc4840780426879282900f130.png

* When we click "Apply Filters" the filter state is updated locally. In the Apply
callback we can access that state which will be keyed filter name and value.
* We should be able to pass an input object for filter constructed from the state. 

```js
filterState.get('fashion_style')

// outut
// {
//    title: 'Above Knee',
//    value: '16432'
// }
```

If we want to filter for "Bottoms" and "Above Knee", we would query:

```gql
{
  products(filter: {category_id: {eq: "28"}, fashion_style: {eq: "16432"}}) {
    total_count
    items {
      name
      sku
    }
  }
}
```

If we wanted to filter for "Buttoms and multiple styles, we would query:

```gql
{
  products(filter: {category_id: {eq: "28"}, fashion_style: {in: ["16432", "some-other-style-id"}}) {
    total_count
    items {
      name
      sku
    }
  }
}
```

**Comment by awilcoxa** [comment]
Currently in progress, removing help wanted label

**Comment by sirugh** [comment]
Category filtering is operational in the search page.
