### ISSUE TITLE
[bug]: RequestError: Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by mrRonyTran** [magento/pwa-studio#1443]
Hello,

I got some errors when I installed PWA.

**Describe the bug:**
RequestError: Error: unable to verify the first certificate.

**To Reproduce**
1. Build artifacts: yarn run build
2. Run the server: yarn run watch:venia

**Please complete the following device information:**
- Ubuntu 18.04
- Magento 2.3.2 CE
- @magento/pwa-studio version 3.0.0
- node v10.16.0
- yarn v1.16.0
- npm v6.9.0
- MAGENTO_BACKEND_URL=https://magentoce232pwa.local

**Screenshots:**

![pwa_1](https://user-images.githubusercontent.com/3252322/61345847-ec955280-a880-11e9-9ed5-34e3ee5d7257.png)
![pwa_2](https://user-images.githubusercontent.com/3252322/61345852-f1f29d00-a880-11e9-864f-dea59bc76642.png)

Please help me if someone has a solution.
Thanks.

**Comment by zetlen** [comment]
Does your backing Magento instance have a valid and locally trusted SSL certificate? If not, can you try using the `http://` URL as your `MAGENTO_BACKEND_URL` instead?

**Comment by rogyar** [comment]
I can confirm that it happens for self-signed certificates. Even if your cert is trusted for all users on your local machine, you will get this error since it's not trusted for Node. There are 2 solutions:
- Use a CA-Signed Certificate.
- Use http protocol instead of https to connect to Magento backend.

**Comment by awilcoxa** [comment]
@zetlen
