### ISSUE TITLE
[feature]: Add support to run pwa-studio tests in a docker container

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1503]
**Is your feature request related to a problem? Please describe.**
Sometimes unit tests pass on local but fail on aws build.

**Describe the solution you'd like**
Add support to run tests on docker container.

**Describe alternatives you've considered**
NA

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment]
@dpatil-magento Can you please add an explanation to this ticket? We should prioritize this because:

- Core devs see unit tests pass locally and fail in CI
- Community contributors can't even see what tests are failing in CI
- Docker environment is part of the product and so devs should be using it and making sure it works

Maybe we can describe the reason to do this by quantifying how much time we lose to diagnosing CI failures.

**Comment by dpatil-magento** [comment]
@zetlen I can take this one as next item but need information as I don't run unit tests :) 
  1. What all reasons which causes to work on local but not on aws?
       a. snapshot available on local but not pushed to github.
       b. ??
       c: ??

Either we can mount local project files to docker and run tests but this approach might not help as local changes might also get mounted OR  start docker with fresh clone of github PR and then run unit tests (as we do on AWS)

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-40

**Comment by zetlen** [comment]
Closing in favor of the internal [JIRA ticket](https://jira.corp.magento.com/browse/PWA-40), since this issue  involves CI access only available to the core team.
