### ISSUE TITLE
[feature] Remove "Home Page" from template title

### ISSUE THREAD

**Issue by revanth0212** [magento/pwa-studio#1616]
This is an issue that was raised in one of the [comments](https://github.com/magento/pwa-studio/pull/1595#discussion_r318213156) of the PR: #1595.

@supernova-at had a nice point of changing the Title of the sample storefront to something that is similar to mainstream e-commerce websites.

@soumya-ashok can you please check [Andy's comment](https://github.com/magento/pwa-studio/pull/1595#discussion_r319137750) and help us with an apt Title for Venia's Home Page?

**Comment by sirugh** [comment]
We set page titles in cms, product, and category pages as well as many of the custom browser side routes. The only place this would be necessary any more is in the `template.html` file. 


Because the template file is rendered for ALL routes and then updated later with data, there is a flash of the incorrect title. As such, I would ask that this be modified to remove the `Home Page` from the template title.

Observe how on refresh (or initial visit) the page title renders "home page" even though I'm on a category:

[![Image from Gyazo](https://i.gyazo.com/2af62a33ef74d58fffe3b0d456551ce6.gif)](https://gyazo.com/2af62a33ef74d58fffe3b0d456551ce6)

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by evan-burrell** [comment]
Just looking a bit at this, I removed the title tag from `template.html`, however, there is still a flash of an incorrect title coming from `packages/venia-ui/lib/components/App/app.js` as the title gets set in there as well. 

```jsx
<Title>
  {formatMessage(
    { id: 'app.titleHome', defaultMessage: 'Home Page' },
    { name: STORE_NAME }
  )}
</Title>
```

![Recordit](http://g.recordit.co/QgiLgSVbvo.gif)

**Comment by sirugh** [comment]
Wow good catch, I assumed the template was the reason but it seems only half. We should also remove the app title set because it is not accurate since the real landing page, or whatever page you're on, should add its own text, and it is wrong to assume it will be the "Home page".

**Comment by evan-burrell** [comment]
@sirugh After looking back through the comments and [Andy's Comment](https://github.com/magento/pwa-studio/pull/1595#discussion_r319137750) on the original PR, would an acceptable solution be to update `template.html` and the title tags in `app.js` to read STORE_NAME - Official Site? And then update the French translation as well to be `Boutique officielle`? If so I'm happy to make a PR.

**Comment by brendanfalkowski** [comment]
Can it just be `STORE_NAME` and drop `Official Site`? It's just a bit too hard of a flex, and it won't fit a lot of businesses.

**Comment by sirugh** [comment]
I agree with @brendanfalkowski, I think just store name is what we want here, as the initial title. I think we can remove the translation for it. Once data fetched we will have the url resolved to a route and can render an updated, accurate title.
