### ISSUE TITLE
[bug]: venia logo does not load on storefront for upward-php.

### ISSUE THREAD

**Issue by dpatil-magento** [magento/pwa-studio#1622]
**Describe the bug**
venia logo does not load on storefront for upward-php.

**To Reproduce**
1. Deploy pwa on cloud starter 
2. Access storefront

**Expected behavior**
Storefront should load with all images.

**Actual**
Venia logo does not load.

**Screenshots**
<img width="879" alt="image" src="https://user-images.githubusercontent.com/40405790/64030122-936d3f80-cb0b-11e9-9c56-09e791b7e688.png">

**Comment by sirugh** [comment]
How do I repro? Do you have a link?

**Comment by cherdman** [comment]
> How do I repro? Do you have a link?

https://develop.pwa-venia.com/
https://magento.pwa-venia.com/

**Comment by sirugh** [comment]
@cherdman I'm not seeing it happen on either of those.

**Comment by dpatil-magento** [comment]
@sirugh @cherdman  Above two runs on `upward-js`  so you dont see issue there.  If we deploy current `develop` branch on cloud starter then we can see the issue.  Let me know if you need cloud starter deployed instance.

**Comment by zetlen** [comment]
@dpatil-magento and I have been working on this since yesterday, though I've been on the road so I've been slower than usual. I have a branch `zetlen/inline-logo-svg` which should fix this issue, but I haven't opened it as a pull request yet.

This issue only appears with UPWARD-PHP on Cloud Pro, and I can't replicate those conditions locally. Therefore @dpatil-magento has to confirm that a pushed change is actually fixing the issue. So far:

- An adjustment to output paths in Webpack config and template config should fix the `logo.png` issue
- Addition of the `parse: text` flag to the UPWARD resolver which delivers `manifest.json` should fix the `manifest.json` issue (that's in the most recent commit, https://github.com/magento/pwa-studio/commit/e6f9a3d72e199f78138625dff272f017a093dbb4).

@dpatil-magento It's ready for you to review, and then if it fixes the issue we can open it as a PR, take a little code review, and do a full end-to-end test run.
