### ISSUE TITLE
[Research Story]: Audit Data Usage for Performance Improvements

### ISSUE THREAD

**Issue by cherdman** [magento/pwa-studio#1624]
**What?**
Examine Venia and Peregrine code for patterns of inefficient data consumption and caching, focusing on GraphQL query performance and Apollo optimizations. Service worker optimizations have been split out into #1673.

**Why?**
Conserving data use increases performance, reduces server load, and lowers bandwidth costs for users; it directly correlates to good user experiences. The PWA Studio app architecture has several areas where it may be possible to greatly increase the efficiency of our data usage, but those optimizations have so far received little attention.

**How?**
- Investigate component usage of GraphQL, ensuring they are efficient and do not overfetch or fetch too frequently
- Examine the cache headers of GraphQL requests and responses, ensuring that they are appropriately labeled and cached based on data volatility
- Look into possible Apollo optimizations using its client and link extension points:
  - Fragment usage and compile-time typing, to fix #1474 and possible optimizations
  - Intelligent caching of business objects, possible using [Hermes](https://github.com/convoyinc/apollo-cache-hermes) or other normalized cache systems
  - Try using [Apollo's new `useQuery` hook](https://www.apollographql.com/docs/react/api/react-hooks/) over the Peregrine `useQuery` hook

**Acceptance Criteria**
- Write-up of audit results and proposed changes
- Actions and next steps created in the form of GitHub issues

**Comment by supernova-at** [comment]
# GraphQL in PWA Studio

PWA Studio uses [GraphQL](https://graphql.org/) to query the [Magento GraphQL API](https://devdocs.magento.com/guides/v2.3/graphql/index.html).

# Dependencies and Configuration

## Apollo

PWA Studio leverages [Apollo](https://www.apollographql.com/docs/react/) to request and cache GraphQL data, and update the UI.

Currently, PWA Studio depends on the [Apollo Client](https://www.apollographql.com/docs/react/v2.5/) and its React view layer integration [react-apollo](https://github.com/apollographql/react-apollo).

### Apollo Client

Instead of using [apollo-boost](https://www.npmjs.com/package/apollo-boost), PWA Studio sets up the Apollo Client manually to take advantage of advanced features.

As such, PWA Studio depends on the following Apollo packages:

#### apollo-client

The Apollo Client is the main engine of Apollo.

A full list of configuration options for `apollo-client` can be found [here](https://www.apollographql.com/docs/react/essentials/get-started/#configuration-options) and [here](https://www.apollographql.com/docs/react/api/apollo-client/#optional-fields) and [#1659](https://github.com/magento/pwa-studio/issues/1659) tracks its configuration within PWA Studio.

#### apollo-cache-inmemory

Apollo's [InMemoryCache](https://www.apollographql.com/docs/react/v2.5/advanced/caching/#inmemorycache) is a normalized data store that serves as our Apollo cache.

A full list of configuration options for `apollo-cache-inmemory` can be found [here](https://www.apollographql.com/docs/react/v2.5/advanced/caching/#configuration).

#### apollo-cache-persist

PWA Studio persists our in-memory cache to `window.localStorage` using `apollo-cache-persist`.
Because the cache is persisted and isn't lost at the end of a user session or when the browser is closed, we realize benefits on startup and in offline mode.

#### apollo-link-http

The [Apollo HTTP Link](https://www.apollographql.com/docs/link/links/http/) actually fetches the GraphQL results from a GraphQL endpoint over an HTTP connection.

A full list of configuration options for `apollo-link-http` can be found [here](https://www.apollographql.com/docs/link/links/http/#options).

### react-apollo

As of `v3.0.0` of `react-apollo` Apollo recommends using hooks for all new Apollo code going forward. In addition to following best practices, PWA Studio can realize a 50% bundle size savings by only installing [@apollo/react-hooks](https://www.npmjs.com/package/@apollo/react-hooks) instead of all of `react-apollo`. See [#1657](https://github.com/magento/pwa-studio/issues/1657) to track the progress of this upgrade.
 
#### useQuery

One of the primary hooks provided by `@apollo/react-hooks` is [useQuery](https://www.apollographql.com/docs/react/api/react-hooks/#usequery).

A full list of configuation options for `useQuery` can be found [here](https://www.apollographql.com/docs/react/api/react-hooks/#options).

#### useMutation 

Another primary hook provided by `@apollo/react-hooks` is [useMutation](https://www.apollographql.com/docs/react/api/react-hooks/#usemutation).

A full list of configuation options for `useMutation` can be found [here](https://www.apollographql.com/docs/react/api/react-hooks/#options-2).

# Performance Considerations

We can directly affect a handful of important performance metrics by fine-tuning our GraphQL usage:
  1. Application load time
  1. The number of roundtrips to the server
  1. Data transfer / payload size
  1. Perceived performance: App responsiveness, etc.

# Relevant Files in PWA Studio

This document has linked to many configuration options to fine-tune our GraphQL usage. 

Here are the relevant files in PWA Studio where we can implement these changes:
  * [Venia Drivers](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/drivers/index.js)
  * [Venia Drivers Adapter](https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/drivers/adapter.js)
  * [ApolloContext hook](https://github.com/magento/pwa-studio/blob/a294b1fbad4c04b5a13e5af34ea26b1050f765f0/packages/peregrine/lib/hooks/useApolloContext.js) (consolidate this)
  * [useQuery hook](https://github.com/magento/pwa-studio/blob/53852e3c269bbe352c1d2ad3016b832c0103788b/packages/peregrine/lib/hooks/useQuery.js) (delete this)
  * [useQueryResult hook](https://github.com/magento/pwa-studio/blob/53852e3c269bbe352c1d2ad3016b832c0103788b/packages/peregrine/lib/hooks/useQuery.js) (delete this)
  * [Venia concept index](https://github.com/magento/pwa-studio/blob/fa0a4c9b45757c272f6b745c546e8b61b1da40db/packages/venia-concept/src/index.js)
  * [Upward Service Resolver](https://github.com/magento/pwa-studio/blob/f9947f25a5265f76ec2582e9023d9a41cb259781/packages/upward-js/lib/resolvers/ServiceResolver.js)
  * Various Docs
  * Various Unit Tests

And as we change dependencies we'll also have to update `package.json` files and [Venia's webpack config](https://github.com/magento/pwa-studio/blob/b35f92ef021c62b76fe56598270d453687fbcaa4/packages/venia-concept/webpack.config.js).

**Comment by supernova-at** [comment]
Here are the things the [GraphQL API caches](https://devdocs.magento.com/guides/v2.3/graphql/caching.html).

**Comment by supernova-at** [comment]
Closing as "completed".
