### ISSUE TITLE
[Research Story] Audit Service Worker for Performance Improvements

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#1673]
**What?**
Examine PWA Studio code for patterns of inefficient data consumption and caching, focusing on the service worker.

**Why?**
Conserving data use increases performance, reduces server load, and lowers bandwidth costs for users; it directly correlates to good user experiences.

**How?**
- Explore ServiceWorker optimizations:
  - Optimize caching strategies for our business use cases (Ex. caching strategy between catalog and customer data, batching of queries, etc.)
  - Consider network conditions and data usage

**Acceptance Criteria**
- Write-up of audit results and proposed changes
- Actions and next steps created in the form of GitHub issues

**Comment by supernova-at** [comment]
This is a great article: https://jakearchibald.com/2014/offline-cookbook/

**Comment by revanth0212** [comment]
# Service Worker

Service Worker can do a lot of things to speed up the app. It can per-cache, pre-fetch, cache on request and update on request among other things. But each of the above-mentioned features of the Service Worker comes with disadvantages of their own depending on the type of client they are serving.

There are mainly 2 types of clients we will be serving:
1. Desktop Environments
2. Mobile Environments

Service Worker implementation needs to be different for different environments it is serving to maximize its potential at providing a smooth and fast app experience.

Also, the implementation should take into account:
1. Network Bandwidth
2. Storage Capabilities
3. CPU Power
4. Battery Power

Although the most important aspect we have to think about is network bandwidth.

#### Desktop Environment

Desktop Environments give the freedom a Service Worker will need to give its best performance. They will be running on a machine with better CPU, better storage capabilities, better network bandwidth and unlimited battery capabilities (assuming it is connected to a power outlet which it does most often).

#### Mobile Environment

Mobile Environments these days have better CPU, better storage and better battery capabilities than their ancestors. But the limiting factor when it gets to these environments is the network capabilities. If the mobile is connected to a WiFi can treat it like a Desktop Environment but most often it would not be the case. In emerging markets the network technology is growing at a faster pace but still needs to be assumed to be slower than a WiFi connection.

## Service Worker Implementation

#### Caching

In this context, we are talking about client-side caching based on the type of resource. If it is a:
1. `Static Resource`: like favicon.ico, manifest.json, fonts, etc, cache it irrespective of the environment because they are not bound to change very often. We can set a validity time of 24 hours which is decent. We take an even granular route of downloading manifest.json every day but downloading fonts and favicon once a month since they don't tend to change very often.
2. `index.html`: will not likely change unless we make changes to the builds. In that case, we can cache index.html and request it in the background. But a problem arises with this method. What if the build changed and we are served a cached version of it? To handle such cases we can make a network call on the load of the app silently in the back to check if something has changed compared to our current build on the UI. If something changed, we can show a prompt on the UI to refresh (just like codesandbox) and bust the cache.
3. `GET call`: will likely change but is better than not having data. We can cache GET call data using a Network First structure so if the network is available we can fetch the data, update cache and return that to the UI. If not, we can return what the cache has for an offline experience. Along with this, we can add a timeout hinting the service worker to return what is has on cache if the network is taking too long and update the cache when the network call is resolved for future uses.

    Also, to improve the performance, we can go with a hybrid structure of retuning what the cache has and also making a network call at the same time. Once the network comes back with data and if that is different from what the cache has, update the cache and return new data to the UI. This involves making changes at the app level since the now the app has to request twice, once to the cache and again to the network.

    This is applicable for both desktop and the mobile environment if they are running on a WiFi connection. 
4. `Image`: will not likely change unless a different resolution is the request of the same image. Always save the highest resolution image in the cache. If the UI requests an image that is in the cache but of a higher resolution than what is requested, return the high-resolution image. If the requested image is of higher resolution than what is in the cache, use the Network First approach.

    Again just like `Get call` this can be a long shot but we can go with a hybrid approach discussed earlier but it comes with its own caveats.
5. `.js File`: these should be treated just like static resources since with #1691 we will be getting js files with hash on them. This will ensure that a bundle is not downloaded unless it is changed. We can go with Cache First approach for these.
6. `Everything else`: as a default option for anything that does not match these, we should be going with Stale While Revalidate option.

### Pre Fetch and Pre Caching

Prefetch and caching improve the performance of the app significantly at the expense of network and memory. Hence it is appropriate only in case of desktop environments and certain mobile environments on WiFi networks. We can prefetch and cache depending on where the user is currently poised. For instance, if we have route based bundling enabled and the user is in category page, prefetch and cache the product page bundle in the background since there is a high chance the user will open a certain product's page. This is also valid for images on the product page. If the user is viewing 2nd image, prefetch and cache 1st and 3rd image if they are not cached already. This will create a nice smooth experience for the user by not downloading all of the images at once or downloading 1 after the other when requested.

### Background Sync

This is applicable to certain data calls like products list, navigation menu, and category list. We can periodically fetch them in the background on a machine with WiFi capabilities. This will allow the UI to load data faster than current implementation where it has to call the graphql server at run time and render once the data is back. Again these should be synced based on the user's current situation. If the user is in the products page, the service worker should only sync data like product availability, ratings, comments etc and not sync categories or CMS page.

## Non Performance Stuff

As much as I can, I tried to limit this post only to the performance benefits of utilizing service worker but there are lot more things we can achieve with service workers like notifications, autosave, offline save and sync once the network is sync, etc. The sky is the limit with Service Workers.

## 2 Cents

There is a lot of potential for using the service worker. A bunch of points mentioned in this post might not be applicable on day 1, but implementing them will help Venia stand out from the bunch.

Behavioral Service Worker is a very new topic and can / should be developed as its own module apart from Venia so the rest of the world can use it as well.

Since we are at a unique point in time where PWA is relatively new, this will set us apart from our competitors by encouraging the community of PWA developers to contribute. We can be the pioneers of Service Workers and PWAs.

**Comment by supernova-at** [comment]
> What if the build changed and we are served a cached version of it?

If the build changed wouldn't it produce a new artifact that would have an updated timestamp and that would invalidate the cache?

> To handle such cases we can make a network call on the load of the app silently in the back to check if something has changed compared to our current build on the UI. If something changed, we can show a prompt on the UI to refresh (just like codesandbox) and bust the cache.

Retailers and users are not going to like that 😬 

> Also, to improve the performance, we can go with a hybrid structure of retuning what the cache has and also making a network call at the same time. Once the network comes back with data and if that is different from what the cache has, update the cache and return new data to the UI. This involves making changes at the app level since the now the app has to request twice, once to the cache and again to the network.

I like this approach and hopefully we can hide those implementation details from the application.

> Background Sync

Super cool!

**Comment by revanth0212** [comment]
> If the build changed wouldn't it produce a new artifact that would have an updated timestamp and that would invalidate the cache?

You will only know that after you request the file. If we can version the index.html or use the time of build as version number, we can utilize background sync structure to request and cache new index.html file.

> Retailers and users are not going to like that 😬

You are right. This will be hard on them. We definitely have to come up with a better solution to this. Something like updating the UI without an explicit refresh.
