### ISSUE TITLE
[feature]: Enable CI/CD to Allow For Running Against Different Cloud Environments

### ISSUE THREAD

**Issue by dhaecker** [magento/pwa-studio#1688]
**Issue**
Current CI/CD for PWA Studio is limited to running against a single cloud environment which prevents other projects from adding seeded data for functional testing. This issue is currently preventing the Page Builder team from adding desired minimal gui functional testing coverage that runs during the CI/CD process

**Acceptance Criteria**
Allow CI/CD for PWA Studio to run against user defined cloud environments

**Please let us know what packages this feature is in regards to:**
- [ ] `pwa-buildpack`

**Comment by dpatil-magento** [comment]
@dhaecker Currently `pwa-tests` have 2 versions.  branch `sampledata_master` runs tests on sample data installed instance. We use this one currently because of https://github.com/magento/pwa-studio/issues/1244.

There is also `master`  `develop` branch where tests first generate data via API's then test and clean-up data.  But here we can not use MFTF CLI commands as testing against remote Magento instance and not local.  Also once API data created sometimes data does not reflect as we are unable to run `indexer:reindex` CLI. But #1244 should solve this.

We can close this ticket unless you are looking for something else.

**Comment by dhaecker** [comment]
@dpatil-magento Since we are blocked by creating data using the Magento APIs in MFTF (#1244), we would have to have seeded data to run our tests against. If we were to add sample data to support Page Builder testing, then we would have to add this sample data to the Home Page since this is the only page that can be used with the current PWA limitations. Since we can only edit the Home Page, this will most likely interfere with your existing tests that rely on data on the Home Page

So it seems like we would either
- Need #1244 resolved along with any rework of your existing functional tests to remove all dependencies on sample data
- Need the ability to run tests against a separate environment to prevent our tests from interfering with your tests (or vice versa)

Let me know if I'm misunderstanding something. Thanks!

**Comment by dpatil-magento** [comment]
Now PWA and PB AWS PR instances running on separate backend instances.
