### ISSUE TITLE
[bug]: getProductDetailByName.graphql is not solid since we can have multiple products with the same name

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#1705]
**Describe the bug**
In `venia-ui` we use the query `getProductDetailByName.graphql` but merchants can have products with the same name. Right now if I remember correctly it picks the first match it finds

**Expected behavior**
Queries the actual product instead of the first match found

**Possible solutions**
Change the variable`name` for `sku` / `parentSku` based on if that's available or not

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Comment by zetlen** [comment]
Ever since we merged #1529 we don't actually have a real reason to have separate GraphQL query files! I think we perhaps shouldn't have them; they are an antipattern, as @jimbo pointed out to me long ago, because queries are supposed to be colocated with views--that's the point of GraphQL's flexibility.

**Comment by awilcoxa** [comment]
fixed in previous PR
