### ISSUE TITLE
[bug]: avoid JS-wrapped text nodes in JSX

### ISSUE THREAD

**Issue by brendanfalkowski** [magento/pwa-studio#1917]
**Describe the bug**
In JSX, replaces simple text nodes like:
`<div>{'The text node'}</div>`

With the simpler:
`<div>The text node</div>`

The extra verbosity to treat a text node as a JS string seems like clutter.

Note: no idea if this does something for somebody, but I'm not a fan of the verbosity and it seems to be the exception. I heard somewhere that VS Code may auto-insert this but IDK.

**Expected behavior**
Plain text nodes don't need to be explicitly wrapped to parse as a JS string.

**Additional context**
I didn't make any changes to JS-wrapped text for attributes, though I think these are overly verbose/weird too compared to a double-quote that's normal in HTML.

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by jimbo** [comment]
We've actually been doing this intentionally, though not rigorously.

Every text node in the app represents tech debt: each one is essentially a hardcoded string that will eventually (read: someday) need to be extracted and run through an internationalization utility. So they'll all be JS expressions eventually.

In the meantime, there may be minor benefits to being explicit with strings instead of running them through React's text node parser, which has more edges.

**Comment by revanth0212** [comment]
Closing because related [PR](https://github.com/magento/pwa-studio/pull/1918) is closed.

**Comment by brendanfalkowski** [comment]
@jimbo Oh I see, maybe you want the opposite PR...

![merry](https://user-images.githubusercontent.com/214924/67236233-ba563c80-f3fd-11e9-986e-b55770d4e35c.gif)
