### ISSUE TITLE
PWA Studio with Stripe and Sagepay

### ISSUE THREAD

**Issue by ankitpatel2931** [magento/pwa-studio#1963]
Hi Team,

I have configured pwa studio with magento 2. Now, I want to know how to implement sage pay payment integration with pwa store front? Could you please provide any guidance how can I implement this?

Thanks.

**Comment by ankitpatel2931** [comment]
Hi Team,

Do you have any update here?

Thanks.

**Comment by tjwiebell** [comment]
@ankitpatel2931 
Payment processors have their own unique way of integrating with your storefronts, so I can't provide you a concrete solution for SagePay, but there's nothing special about PWA Studio you need to account for. SagePay should have documentation for how to integrate their gateway in your site, and the extension you're using for Magento should support those APIs. We consider Magento headless for our purposes, so as long as there are API endpoints to support this payment method, those can be used in PWA Studio.

We currently support Braintree, which has a node package that creates drop-in web forms, returns our app a nonce, that we pass to Magento on checkout. If SagePay provides something similar, you can use that as a reference:

https://github.com/magento/pwa-studio/blob/develop/packages/venia-ui/lib/components/Checkout/braintreeDropin.js

Going to close this out since it's just a general question. Feel free to head over to our community Slack channel if you have any additional questions:

https://magentocommeng.slack.com/channels/pwa

**Comment by ankitpatel2931** [comment]
Hi @tjwiebell ,

Thanks for the Update.
It's really helpful.

**Comment by maheshwaran-1343** [comment]
Hi @tjwiebell , @ankitpatel2931 any one have managed to get stripe integration working with PWA studio.

**Comment by zxiaoh** [comment]
> Hi @tjwiebell , @ankitpatel2931 any one have managed to get stripe integration working with PWA studio.

So do you have a solution for integrity? Instead of providing 2 or more links tell us that multiple payments can be supported!
