### ISSUE TITLE
Page Builder content: Image element duplicates on the web-site

### ISSUE THREAD

**Issue by RuslanPloskonosEWave** [magento/pwa-studio#2031]
**Describe the bug**
If **Image** element is added for Product using Page Builder then when user open this Product on the Front-End side and check added Page Builder content - Image duplicates on the web-site (see attached video)

**To reproduce**
1. Go to 'Magento admin page'
2. Create New Product
3. While creating New Product, go to Content->Description
4. Click on the **Edit with Page Builder** button
5. Drag and drop Image (Media->Image on the left panel) element
6. Select any image for element
7. Save Product and go to the web-site
8. Open Product and check page with Page Builder content 

**Expected behavior**
Image shouldn't duplicate on the web-site.

**Video**
![Image-element-is-duplicted-on-Front-end-side](https://user-images.githubusercontent.com/58929037/70883657-bcdfa780-1fe4-11ea-8bbb-dd2d98f7ba65.gif)

**Device information:**
 - Device: iPhone, PC, Mac
 - OS: iOS, Windows 10
 - Browser: Chrome, Safari, FF
 - Magento Version: ver. 2.3.3

**Comment by davemacaulay** [comment]
Page Builder doesn't current support rendering within Catalog Products out of the box, we only support CMS Pages. 

The issue you're seeing is due to PWA Studio simply rendering the master storage format as direct HTML. If you have the same content in a CMS Page you'll see this is handled correctly.
