### ISSUE TITLE
can any one help Related to push notification

### ISSUE THREAD

**Issue by vpberiya** [magento/pwa-studio#2160]
Push notification is implemented already or not?
if implemented then please help how to use and know the folder structure there implement.

**Comment by awilcoxa** [comment]
Hi @vpberiya this is a topic better suited for the community [#pwa ](https://magentocommeng.slack.com/messages/C71HNKYS2) slack channel. 

We currently don't have specific dev docs around enabling push notifications but it's certainly possible today. 

I'm closing this ticket for now since this is more of a best practice/implementation question.
