### ISSUE TITLE
[feature]: Extended prices for cart details

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#2172]
**Is your feature request related to a problem? Please describe.**
Since 2.3.4 we have more prices available via GraphQL, we should update the cart detail prices.

**Describe the solution you'd like**
I want all possible prices to be available in my cart context

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by Jordaneisenburger** [comment]
PR open @ https://github.com/magento/pwa-studio/pull/2173

**Comment by sirugh** [comment]
@Jordaneisenburger have you looked at the new cart work and how we fetch/request data there? It's a little more divided in that there's not _one place_ where you can define/request data like there is with the cart context. That's because the new approach is based more on requesting data as necessary *per component* instead of all at once like we might expect with REST.

I'm hesitant to add new fields to the old query that aren't used at all in the front end. And I'm even more hesitant to touch code that may be deprecated in the (near?) future when we switch over to the new cart and checkout experience. What do you think about working with UX to come up with a use case for these fields in the new cart/checkout pages?

**Comment by Jordaneisenburger** [comment]
Awesome! Totally missed that one, my bad
