### ISSUE TITLE
[bug]: Footer gets pushed out of viewport even if page content is short

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#2177]
**Describe the bug**
Regardless of the height of a pages' content, the footer will never be within the viewport.

**To reproduce**
1. Go to 'https://venia.magento.com/'

**Expected behavior**
As the page's content is small, just a simple list of categories, I would expect to see the footer also within the viewport, but it's completely out of view, and I have to scroll to be able to see it

**Screenshots**
![image](https://user-images.githubusercontent.com/18253422/74895803-8d815880-53e2-11ea-8ddf-c0e064f9e01d.png)

**Additional context**
The reason this issue is occuring is due to the `.page` element being given a `min-height` of `100vh`. Viewport units are great, but they should be used very carefully, because they have unintended consequences, one of which I believe this is.

**Possible solutions**
The fix is to go back to the "old" way of pushing a footer to the bottom of the page: `height: 100%` on `html`, `body` and any parent containers (in this case, `#root` as well)

**Please complete the following device information:**
 - All Devices
 - All OS's
 - All browsers
 - PWA Studio Version: 5

**Please let us know what packages this bug is in regards to:**
- [x] `venia-ui`

**Comment by jimbo** [comment]
> As the page's content is small, just a simple list of categories, I would expect to see the footer also within the viewport, but it's completely out of view, and I have to scroll to be able to see it

Thanks for creating this issue. Believe it or not, the current implementation is the expected behavior. The `min-height: 100vh` here is simply enforcing a design requirement, which is that a page should fill at least that much vertical space.

The real issue here is that the home page is too sparse. It's a home page, so it should contain big hero images, banners, and calls to action, but right now it's still very much a placeholder. We have a story to flesh the home page out, and it's coming up soon in our queue.

**Comment by luke-denton-aligent** [comment]
Thanks for the response @jimbo. Does that mean this CSS doesn't get applied to non-home page pages? Certainly the home page will have more than just a category jump menu, but not every page is a home page, and there could very well be pages that don't have _that_ much content. Perhaps a simple contact hours page, or about us page etc.
