### ISSUE TITLE
Venia storefront is not accessible

### ISSUE THREAD

**Issue by megastallman** [magento/pwa-studio#2212]
I'm getting `{"error":"No definition for veniaResponse.status"}` in a browser.

1. Install venia-concept 5.0.1 with yarn, on magento 2.3.4 fresh install.
2. Use the php module-upward-connector 1.0.0.
3. In Magento Admin interface, navigate to: Stores → Configuration → General → Web → Upwards Configuration
4. Set the UPWARD file yaml to: /srv/public_html/node_modules/@magento/venia-concept/upward.yml
5. Double check its contents(uncommented):
`status: veniaResponse.status
headers: veniaResponse.headers
body: veniaResponse.body`
6. All caches cleaned and assets rebuilt.

**Expected behavior**
I expect to get to the storefront WEB-UI. With or without sample data(tried both options).

**Please let us know what packages this bug is in regards to:**
- [* ] `venia-concept`

**Comment by tjwiebell** [comment]
@megastallman

You also need two runtime environment variables, so please be sure that `MAGENTO_BACKEND_URL` and `NODE_ENV` or set. Though I think there's some minor confusion here.

I'm going to see if we can prioritize some documentation updates, because it may not be clear that the instructions for the upward-connector are intended to imply you're creating your own application (venia-concept) and publishing to npm, or building locally. The published app at @magento/venia-concept has a hard dependency on the `MAGENTO_BACKEND_URL` we used at build time, so I would expect some odd behavior if you're trying to use a different backend with that published bundle. It _probably_ would work, but here are steps I would follow (and what we'll get added to documentation):

(all of these commands should work with npm too)
1. yarn create @magento/pwa (use your own Magento backend when you get to that step)
2. Run `yarn` to install
3. Run `yarn build` to build your bundle in `/dist`
4. Configure upward-connector to use `/dist/upward.yml`
5. Make sure you have runtime environment variables set for `MAGENTO_BACKEND_URL` and `NODE_ENV=production`
6. Clear caches and you should now be good to go to access your storefront

Let us know if you're still encountering any problems.

**Comment by megastallman** [comment]
Thanks @tjwiebell 
Probably, I've missed the variables. Looks like working now.

**Comment by sankhalainfo** [comment]
Sorry I am new to this. Can you please help me to understand how to provide run time variable. We are getting exact same issue that "{"error":"No definition for env.MAGENTO_BACKEND_URL"}".

1. pwa-studio/packages/venia-concept/.env has set the required variable.
2. yarn build has been done and dist folder is configured in Upward PHP file
3. Do i need to keep on yarn watch:venia in order to get it working. 

Please suggest how to get rid of the above error.

**Comment by sirugh** [comment]
@sankhalainfo this issue is closed - can you open a new issue and provide your full error stack trace and some context for us? Thanks.

**Comment by plamenh** [comment]
This is extremely unclear. environment variables for PHP or node? None of these seem to work with our setup (neither setting variables in index.php (PHP), nor setting them at build time (node).
