### ISSUE TITLE
[bug]: `yarn create @magento/pwa` failing - "Unexpected end of data"

### ISSUE THREAD

**Issue by luke-denton-aligent** [magento/pwa-studio#2238]
**Describe the bug**
I am unable to create a new Magento PWA Studio project using the `yarn create` syntax. `npm init` works as expected

**To reproduce**
1. Create a new directory
2. cd into directory
3. Run `yarn create @magento/pwa`

**Expected behavior**
Expect the interactive questionnaire to be started

**Screenshots**
![image](https://user-images.githubusercontent.com/18253422/76366028-b8732280-6378-11ea-9dd2-a2daa5738fbe.png)

**Additional context**
As mentioned

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: PC
 - OS [e.g. iOS8.1, Windows 10]: Centos 7
 - Browser [e.g. Chrome, Safari]: N/A
 - Browser Version [e.g. 22]: N/A
 - Magento Version: N/A
 - PWA Studio Version: N/A
 - NPM version `npm -v`: 6.13.4
 - Node Version `node -v`: 12.16.1

**Please let us know what packages this bug is in regards to:**
- [x] `create-pwa`

**Comment by awilcoxa** [comment]
Created in Jira backlog for prioritization/grooming

**Comment by awilcoxa** [comment]
Marked as P2S1

**Comment by tjwiebell** [comment]
@luke-denton-aligent - Are you still seeing this error? It appears to be related to the `event-stream` exploit from 2018, where npm unpublished this version, but I'm not quite sure where that dependency is coming from. Its not a direct dependency that I can find in the repo, so might be an outdated library that has since been updated.

https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

I've tried both Node 10 and 12 with no problem (though 12 not officially supported at the moment, but appears to be no compatibility problems). On the off chance your global space is retaining an old version, try `yarn global remove @magento/create-pwa` and running the generator again.

Linux would be the only differentiator here, so please confirm this is still a problem, and I'll get a CentOS container up to help run this down.

**Comment by luke-denton-aligent** [comment]
Hi @tjwiebell, thanks for looking into this.

I've just re-tried, and rather than getting "Unexpected end of data", I'm now getting "404 Not Found". Very odd.

![image](https://user-images.githubusercontent.com/18253422/78726100-4807f300-7970-11ea-9f01-804be18ae3bd.png)

As we can see in the image above, I then tried your suggestion of removing `@magento/create-pwa` from the global scope, but I don't have it installed globally.

We're running `CentOS Linux release 7.7.1908` specifically, in case that helps

**Comment by tjwiebell** [comment]
@luke-denton-aligent - I've followed these steps and have not had any luck re-creating your error. I did get `node-gyp` warning output because I didn't have Python installed, but still got to the wizard prompt, since it was an optionalDependency.

1. `docker pull centos:centos7.7.1908`
2. `docker run -i -t centos:centos7.7.1908`
3. Install NVM: `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash` (ran provided export command so I didn't have to source config by closing/opening new session)
4. `nvm install 10`
5. `nvm use 10`
6. Install yarn: `curl -o- -L https://yarnpkg.com/install.sh | bash` (ran provided export command again)
7. `yarn create @magento/pwa`

Do you think you could provide a container or steps I can follow to re-create in a fresh CentOS container? I'm suspecting this is somehow tied in with something in your npm cache, but you very rarely ever need to concern yourself with that (or ever manually clean it up).

**Comment by luke-denton-aligent** [comment]
@tjwiebell Hmm, that's interesting.. I'm happy to mark this issue as invalid then, as I think it's pretty clear to just be an issue with my machine (I have seen people on Slack using the command without any issues 🤷).. The other weird part is that swapping to the `npm` create command worked perfectly fine..
Anyway, thank you for looking into this, as I said, happy for this to be closed and chalked up to a problem with my machine specifically

**Comment by tjwiebell** [comment]
@luke-denton-aligent - New release should be published at the end of April, maybe that will resolve this if its a cache problem. My only other idea is to check your `.yarnrc` for custom registries, or you could try a manual wipe of `@magento/create-pwa` from the yarn cache.

Closing at your request, but please re-open if you track down some reproducible steps.
