### ISSUE TITLE
[feature]: Publish compiled npm packages

### ISSUE THREAD

**Issue by paales** [magento/pwa-studio#2410]
**Is your feature request related to a problem? Please describe.**

So I’m trying to use the `@magento/venia-ui` and `@magento/peregrine` as a library but it seems the packages are only published on NPM as source versions.

Because of this I'm running into issues like this:
https://github.com/zeit/next.js/blob/master/errors/css-npm.md

**Describe the solution you'd like**
I'd like for the ability to use the packages as just that, a package, without requiring me to use Magento's build system and have instructions how I'd use it in that configuration

**Describe alternatives you've considered**
I'm currently trying to build the package directly and trying to create the minimal webpack config, but that might be practically impossible.

**Please let us know what packages this feature is in regards to:**
- [ ] `venia-concept`
- [x] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by awilcoxa** [comment]
created in Jira backlog for triage (PWA-656)

**Comment by zetlen** [comment]
Hi Paul. Thanks for your patience while we catch up with a backlog of worthy discussions.

For a while, we did publish transpiled CommonJS for Peregrine. We decided to stop, though, because we strongly advocate using ES Modules everywhere possible, and didn't want to make it easier for folks to make what we considered to be a bad choice for performance.

It is true that this is easier to fix if you're using Buildpack and the `configureWebpack` function. The `special` parameter lets you set flags which help Webpack to configure its loaders right for some (not all) dependencies.

But this is a common problem for other projects that use Webpack as well. In Googling for "nextjs css node_modules" I found a lot of similar questions and concerns, especially with more recent releases. And it looks like someone has made a Next plugin for this very thing!

https://www.npmjs.com/package/next-transpile-modules declares in its FAQ that it supports CSS Modules since Next 9.2 came out.

I think this is a common enough issue in the React and Webpack ecosystem that good solutions, like better bundler configuration, will emerge more and more just like the above NextJS plugin has. So I don't think we will move to publishing CommonJS modules, which have a significant analysis and performance cost, when the right answers are becoming more available.
