### ISSUE TITLE
Node version requirement - >= 10.x LTS

### ISSUE THREAD

**Issue by WestArjan** [magento/pwa-studio#2438]
Hey,

I was wondering if PWA-studio is also stable with the latest LTS node version ( 12.x ). I am running on Fedora 31 at the moment and I can't seem to find an available repository for Node.js that is lower than version 10.17. Will continue running at 12.17 LTS give me issues?

**Comment by paales** [comment]
The latest release is only compatible with node 10, the current develop branch is compatible with node 12. Created this ticket to alleviate this https://github.com/magento/pwa-studio/issues/2431

**Comment by tjwiebell** [comment]
@WestArjan - as mentioned, we expanded support for node12 in `develop`, and will be released in line with Magento `2.4.0` currently estimated mid-July.

Since this seems to be a general question I'm going to close this out. I see you've found the #pwa channel over on our Community Slack, so feel free to message me if you have any followup questions.
