### ISSUE TITLE
[feature]: Basic desktop improvements for Venia - Mega Menu

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#2805]
<!--
Thank you for taking the time to report this issue!
GitHub Issues should only be created for problems/topics related to this project's codebase.

Before submitting this issue, please make sure you are complying with our Code of Conduct:
https://github.com/magento/pwa-studio/blob/develop/.github/CODE*OF*CONDUCT.md

Issues that do not comply with our Code of Conduct or do not contain enough information may be closed at the maintainers' discretion.

Feel free to remove this section before creating this issue.
--]

**Is your feature request related to a problem? Please describe.**
The current version of Venia is optimized for mobile with minimal support OOTB for desktop including menus/navigation. This is a frequent customization part of our larger roadmap for PWA Studio and PWA-651. http://bitly.com/pwaroadmap

**Describe the solution you'd like**
Basic desktop improvements and "mega-menu" should include support for dynamic categories, subcategories that are driven from GraphQL and the Magento 2 admin similar to the current/mobile navigation. Layout and specifications are part of the Venia styleguide but redlines are included as a reference.

- The highest level categories in the root category are displayed within the top navigational bar
- If the categories in the top navigational bar have sub categories a dropdown is displayed on hover
- Categories in the top navigation bar are still navigation elements and can be clicked on to visit that category

Luma implements a pseudo mega menu solution using just simple dropdowns:
[img width="740" alt="image" src="https://user-images.githubusercontent.com/1774374/96888404-34733400-144b-11eb-81be-2585b2496988.png">

**Describe alternatives you've considered**
Options to simplify and iterate should be considered. Future phases to include category/CMS imagery will be considered.

**Additional context**
![Mega*menu*clean v3](https://user-images.githubusercontent.com/2686596/97023430-1d9c1280-151b-11eb-85ef-78463df00ec0.png)
![Mega*menu*specs v3](https://user-images.githubusercontent.com/2686596/97023437-1ffe6c80-151b-11eb-9abd-fcb8efe44c52.png)

In addition to several extensions available, these PWA Studio launches have mega menus implemented:
https://uk.elemis.com
http://thewhiskybarrel.com

**Please let us know what packages this feature is in regards to:**
- <X] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [X] `peregrine`
- [X] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ > `create-pwa`

Scanerio's Verified - 
1.  Mega menu UI in all browsers.
2. Mega menu main and sub categories display and functionality on click.
3. Verified with different URL suffixes.
4. Verified Venia upgrade flow
5. Verified on AWS and cloud deployed instances.
6. Ran MFTF, 2 tests needs fix though.
7. Verified Mega menu on different pages of Venia
8. Verified on different store views English, French.

**Comment by ericerway** [comment]
Minor updates to the design/spec added. 👍

**Comment by huykon** [comment]
@ericerway  I have seen the Women category (highest level) have 5 sub-categories are: What's New, Bottom, Tops, Outerwear, Accessories. If that have more than 5 sub-categories, what the next sub-category will show on?

**Comment by schensley** [comment]
@huykon Great question! Ideally the area allowed for the menu items would be constructed in such a way that it would allow for that area to stretch to match the full-width of the header (here maxed at 1440px), this might allow for an additional column, BUT of course there may be merchants who have many sub-categories in which case there should be allowed to stack -- this would also be necessary when the screen size doesn't accommodate this optimal and orderly layout. In practical application the mega-menu will require some frontend design finesse to arrange columns and stacked sub-categories to provide a well organized and visually appealing layout.

**Comment by Frodigo** [comment]
@magento I am working on this

**Comment by Frodigo** [comment]
@ericerway I have one question. Take a look at the attached screenshot:

![Screen Shot 2020-11-07 at 17 50 39](https://user-images.githubusercontent.com/11998249/98447062-572b6b00-2122-11eb-9201-d0c032341f60.png) 

I suppose that "Women" is an active category name, but I don't understand from the 'Clothing' phrase came from.

**Comment by schensley** [comment]
Hi @Frodigo I think that is simply meant to be a reference label for reenforce which category was tapped in the navigation, and the designer might have taken some liberties adding "clothing" to give it greater separation in terms of hierarchy. I suppose it could serve as a breadcrumb which could be handy if this menu were to appear as an entire page where instead of "Clothing" it led with "Home" or something.

**Comment by sirugh** [comment]
@schensley could we just say that for this iteration we _dont_ include the breadcrumb/thing at the top as indicated? Just want to provide clear instructions for @Frodigo .

**Comment by Frodigo** [comment]
@schensley @sirugh I think that we can include this breadcrumb here. I can use the root category name as the first breadcrumb item and the hovered first-level category name as the second breadcrumb item.

Please confirm that it is OK for you. 

Thanks,
Marcin

**Comment by schensley** [comment]
@Frodigo that sounds like that would accomplish things nicely.

**Comment by brendanfalkowski** [comment]
Two cents & grain of salt — breadcrumbs are just plain weird to include *inside* a menu. The level-1 categories are the root of all nav from the user's perspective. The menu shouldn't need orientation.

Worse, in practice, I don't think stores frequently rename "root category" or develop any content there because it's too broad to have a point. That's what the home page serves. With this UI a bunch of stores will show "Root Category / Women" here, which is *chef's kiss*.

I wouldn't put this in core Venia simply because it's one of those things implementors will have to change on every project.

This would be better served by a simple "View all in women" link because that nav anchors only toggles the menu (I'm assuming), but this kind of depends on the store's choices. Many don't implement a renderable level-0 (root) or level-1 category because it's too broad. They only link to level-2 downward because it's targeted enough.

**Comment by ericerway** [comment]
@frodigo any updates since the demo? Let us know when you think even a basic PR would be ready when you have a moment. Thanks!

**Comment by Frodigo** [comment]
Hi @ericerway, I plan to create PR this week, stay tuned!

**Comment by sirugh** [comment]
@magento export issue to Jira project PWA as Story

**Comment by magento-engcom-team** [comment]
:white_check_mark: Jira issue (https://jira.corp.magento.com/browse/PWA-1285) is successfully created for this issue.

**Comment by schensley** [comment]
@Frodigo I just had a look at the mega menu work you did and while it was designed pretty much to the UI design provided, I think there are some _tweaks_ that should be made.

- Let's discard the breadcrumb text. Initially I thought it might help provide better context, but it seems to add noise and maybe some confusion. We'll allow the underline in the Main Nav list to help the shopper know what category they are looking at.
- Since in this instance there are not sub-categories in the list I suppose the categories (ex. Belts, Jewelry, Scarves) are acting as those headings, so let's have those be "semi-bold" or match the weight in the categories as they appear in the Main Nav list.  If there were sub-categories beneath these cat. headings in the menu then they would assume a Regular weight.
- Finally, let's ensure that items (group of columns) alignment is centered to the width of the Main Nav list. I realize with only two or three categories it can look a little "ragged", so maybe it already is aligned.

Attaching some visuals.  Sorry for the tweaks, but after seeing the good work you've done I think some of the original direction was misguided.  Thanks!

![change](https://user-images.githubusercontent.com/19538346/105236253-a4b85100-5b31-11eb-81ae-552fc8e4801c.png)
![revised_specs](https://user-images.githubusercontent.com/19538346/105236265-a5e97e00-5b31-11eb-8b8c-b7abf84056b8.png)
![revised_clean](https://user-images.githubusercontent.com/19538346/105236315-a8e46e80-5b31-11eb-8bee-54fd67dc4d22.png)

**Comment by Frodigo** [comment]
Hey, @schensley thanks for your feedback! I'll add changes soon.

**Comment by schensley** [comment]
@Frodigo thank you, sir.

**Comment by Frodigo** [comment]
@schensley I added changes based on your comments and updated PR. 

![Screenshot 2021-02-04 at 07 47 47](https://user-images.githubusercontent.com/11998249/106860957-68562a80-66c5-11eb-96a5-1bcce75fdf8a.png)
![Screenshot 2021-02-04 at 07 48 07](https://user-images.githubusercontent.com/11998249/106860965-6ab88480-66c5-11eb-9a1b-c4e10e697239.png)

**Comment by schensley** [comment]
Thank you @Frodigo I think things are looking much cleaner. 
The second sample you provided reveals something. The spacing between categories should be greater to more easily differentiate where one category title ends and the next one begins. Maybe increasing that minimum space to ~32px to 40px, room to span from the left edge of the logo to the right edge of the basket icon in the header, then wrap if it exceeds the space, again allowing enough padding between them that it's clear they are distinct. Thanks.

**Comment by Frodigo** [comment]
Hey @schensley, I added final adjustments.  
![Screenshot 2021-02-22 at 19 55 52](https://user-images.githubusercontent.com/11998249/108763111-437d0680-7551-11eb-987f-d3e20a2bfa37.png)
![Screenshot 2021-02-22 at 19 55 44](https://user-images.githubusercontent.com/11998249/108763119-4677f700-7551-11eb-91dd-4e62de744fd2.png)

**Comment by schensley** [comment]
@Frodigo excellent.  Thank you!  UI/UX approved.
