### ISSUE TITLE
[bug]: Product - change colour add more images instead of just change colour

### ISSUE THREAD

**Issue by savlo** [magento/pwa-studio#2808]
**Describe the bug**
On product page, changing the colour of a product will add at the beginning of the carousel one more image.

**To reproduce**
1. Go to any product page where are multiple colours
2. Press any of the colours

**Expected behavior**
The images will just change with the right colour, but not change the images number

**Screenshots**
[https://paste.pics/e8dae5ff0767b31912549595f42108e7](https://paste.pics/e8dae5ff0767b31912549595f42108e7)
[https://paste.pics/816353f29d43b21de53dc32bb25e9c8b](https://paste.pics/816353f29d43b21de53dc32bb25e9c8b)

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: MAC
 - OS [e.g. iOS8.1, Windows 10]: iOS 
 - Browser [e.g. Chrome, Safari]: Mozilla
 - Browser Version [e.g. 22]: latest
 - Magento Version: 2.4.0
 - PWA Studio Version: 8.0.0
 - NPM version `npm -v`: 6.14.8
 - Node Version `node -v`: -

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [X] `venia-ui`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by sirugh** [comment]
@savlo this is not a bug - when you select a color the corresponding images for that color is "prepended" to the beginning of the list of images, and the user's position in the image array is "moved" back to the beginning. You can see [here](https://github.com/magento/pwa-studio/blob/develop/packages/peregrine/lib/talons/ProductFullDetail/useProductFullDetail.js#L87) how we prepend the images onto the product's other images for a chosen variant/option.

Technically, and in short, we do this because our sample data for the demo storefront is configured where each product variant has a single entry. We **could** make it just show only the images for the variant, but that feels like a bad UX since you can't see the other product images after selecting a color.

[![Image from Gyazo](https://i.gyazo.com/682ac84642c1ac6d0f4160ee8517dde7.gif)](https://gyazo.com/682ac84642c1ac6d0f4160ee8517dde7)

This is expected:

[![Image from Gyazo](https://i.gyazo.com/c1059f2f26e7027e4ae804c1775d8983.gif)](https://gyazo.com/c1059f2f26e7027e4ae804c1775d8983)
