### ISSUE TITLE
How do you edit the PWA manifest after scaffolding?

### ISSUE THREAD

**Issue by Skavengerr** [magento/pwa-studio#2908]
Hello, now when i opening my manifest in builded project i see that one
![image](https://user-images.githubusercontent.com/41162650/102212174-71085c80-3edd-11eb-92a6-be509ba9da15.png)
I tried adding mine in the root of the project, but nothing worked.
So how can I edit my manifest?

**Comment by huykon** [comment]
You can edit manifest.json on path: `packages/venia-ui/venia-static/manifest.json`

**Comment by Skavengerr** [comment]
@huykon Yeah, but it's in a node_modules and if I reinstall them I have to edit again

**Comment by huykon** [comment]
no. This file not in path of node_modules

**Comment by Skavengerr** [comment]
@huykon 
I created a project with 'yarn create @magento/pwa' and after installing the project I have this structure
![image](https://user-images.githubusercontent.com/41162650/102314844-cb57fa80-3f7b-11eb-9e82-f2aef48d4be2.png)

**Comment by sirugh** [comment]
@Skavengerr One idea - clone `venia-static` to a new folder in your project root and update your `upward.yml` to route to a different static folder instead of `venia-static`. That might work. I might be missing something but I would have thought it'd be easy to modify the manifest after scaffolding. @revanth0212 you've got some experience around this directory/upward. Any thoughts?

**Comment by revanth0212** [comment]
Theoretically, the workaround that @sirugh suggested should work, since we are adding a new `manifest.json` file to the project and the new scaffolded app's `template.html` has a link mentioned this way `<link rel="manifest" href="/manifest.json">`.

That said, I will create a ticket in our backlog to make the scaffold logic to eject a manifest.json file during the creation process. Not sure why we are not ejecting one, maybe @zetlen knows.

**Comment by revanth0212** [comment]
Hello, @Skavengerr I have created an internal ticket on our backlog to investigate the issue. Thank you for your question, please let us know if the workaround that @sirugh suggested works.

**Comment by Skavengerr** [comment]
@revanth0212  @sirugh Thank's a lot, I will try it. Could you provide an example of updated upward.yml?
