### ISSUE TITLE
[bug]: Duplicate thumbnails are generated on PDP swatch change

### ISSUE THREAD

**Issue by drpayyne** [magento/pwa-studio#2931]
**Describe the bug**

In the swatch images PDP of Venia with Venia sample data installed, duplicate thumbnails are being generated on the left when switching between the swatch colors.

**To reproduce**
1. Go to any product with swatch images for example http://0.0.0.0:10000/carola-infinity-scarf.html
2. Switch between all swatch icons
3. Whenever the user moves from primary (default) image to any secondary image, a new thumbnail for chosen color is generated.
4. When moving multiple times, over 5 images are created which is not right.

**Expected behavior**

Image thumbnails should not be duplicated 

**Screenshots**
![image](https://user-images.githubusercontent.com/22623301/103888024-0926e980-510a-11eb-83d3-fb98acf9b2e9.png)
![image](https://user-images.githubusercontent.com/22623301/103888047-13e17e80-510a-11eb-9cda-2a32e3e0a417.png)
![image](https://user-images.githubusercontent.com/22623301/103888067-1c39b980-510a-11eb-8944-9dd97d4fca97.png)
![image](https://user-images.githubusercontent.com/22623301/103888083-22c83100-510a-11eb-811d-41b2057b7634.png)

**Additional context**

**Possible solutions**
Add any ideas about possible solutions to the problem here.

**Please complete the following device information:**
 - Device [e.g. iPhone6, PC, Mac, Pixel3]: Laptop
 - OS [e.g. iOS8.1, Windows 10]: Ubuntu 20
 - Browser [e.g. Chrome, Safari]: Firefox 
 - Browser Version [e.g. 22]: 84.0 (64-bit)
 - Magento Version: 2.4.1
 - PWA Studio Version: latest
 - NPM version `npm -v`: 6.14.6
 - Node Version `node -v`: 12.18.3

**Please let us know what packages this bug is in regards to:**
- [ ] `venia-concept`
- [ ] `venia-ui`
- [ ] `pwa-buildpack`
- [x] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`
- [ ] `create-pwa`

**Comment by drpayyne** [comment]
Note: switching between secondary colors doesn't generate duplicates

**Comment by sirugh** [comment]
I tried this locally using the latest release candidate, `v9.0.0-rc1` and it looks like this is no longer an issue. If I'm incorrect, or misunderstood the repro steps, please let me know and we can reopen the issue. Thanks!

[![Image from Gyazo](https://i.gyazo.com/435a80a500a73ed78f5856cc0687b783.gif)](https://gyazo.com/435a80a500a73ed78f5856cc0687b783)

**Comment by aigarsMage** [comment]
Having the same issue on latest pwa and magento

**Comment by jh0l** [comment]
This is my brief understanding but it seems at least in the sample store data, for each product it's default media entry is also a variant. So as the redundant variant has the same `file` and `label` attributes as the default entries, because of how a thumbnail's key is created in the carousel component, unique thumbnails generate the same key so react loses track of the list of thumbnails.
You can see that [in carousel.js at #L55](https://github.com/magento/pwa-studio/blob/4e43101350e51a0b95817d50c5313e1684fb2ca4/packages/venia-ui/lib/components/ProductImageCarousel/carousel.js#L55).
I found that using the item's id fixed the issue.
