### ISSUE TITLE
Overriding default route

### ISSUE THREAD

**Issue by Skavengerr** [magento/pwa-studio#2971]
Hello, how can I override default route in pwa? I need it because I should redirect to our magento checkout.

![image](https://user-images.githubusercontent.com/41162650/106421007-8c670100-6464-11eb-93e5-76a313574d04.png)

![image](https://user-images.githubusercontent.com/41162650/105863482-9cf92080-5ff9-11eb-826c-19e727f130a1.png)

Error: @magento/venia-ui: Conflict in "routes" target. "@magento/venia-ui" is trying to add a route {"name":"CheckoutPage","pattern":"/checkout","exact":true,"path":"./src/app/pages/Checkout"}, but "undefined" has already declared that route pattern: true
![image](https://user-images.githubusercontent.com/41162650/105863528-a6828880-5ff9-11eb-8de3-e9ed10ea1edc.png)

**Comment by sirugh** [comment]
Hi @Skavengerr sorry I'm so delayed in responding. In the future I would recommend bringing these sorts of questions to the slack channel as you're likely to reach a wider audience and get a quicker answer.

Anyways, I'm not sure why this isn't working for you, but it seems to work on v9 (tested on v9.0.0-rc.1).

This is my local-intercept.js
```
function localIntercept(targets) {
    targets.of('@magento/venia-ui').routes.tap(routes => {
        routes.push({
            name: 'Checkout',
            pattern: '/checkout',
            exact: true,
            path: require.resolve('./src/checkout')
        });
        return routes;
    });
}

module.exports = localIntercept;
```

And I have a component named `checkout.js` that is just a div. When I went to `/checkout`, it rendered my component rather than the PWA Studio default checkout page/route.

So I would suggest trying this on the latest version, once it is released. If you still run into the problem, please open a new issue and fill out as much information as possible such as node version, pwa studio version. Thanks!
