### ISSUE TITLE
[bug]: When clicking a submenu in the mega the submenu won't close

### ISSUE THREAD

**Issue by Jordaneisenburger** [magento/pwa-studio#3070]
**Describe the bug**

When a user clicks on a submenu item in the new mega menu the site navigates to the new page but the submenu stays open. When your submenu has more children this becomes very annoying.

(shame on me I knew this bug would surface and totally forgot to report it whilst the PR was open)

**To reproduce**

1. Hover over a menu item that has a submenu
1. Click on a submenu item
1. Page navigates
1. Menu stays open

**Expected behavior**

I'd expect the megaMenu to close on navigate as a reference check <https://www.eleganza.nl/] where i've fixed the issue

**Screenshots**

**Possible solutions**

I've solved it by toggling a new class that has the exact same styling except the hover state. Because this is a class with a different name/generated hash it the browser will remove the hover state.

**Debug Report**

 

**Please let us know what packages this bug is in regards to:**
 - [ ] `venia-concept`
 - [x] `venia-ui`
 - [ ] `pwa-buildpack`
 - [x] `peregrine`
 - [ ] `pwa-devdocs`
 - [ ] `upward-js`
 - [ ] `upward-spec`
 - [ > `create-pwa`

**Comment by sirugh** [comment]
I cant repro this on develop.pwa-venia.com. Can you provide an example of how we should configure some sample data to repro the issue?

[![Image from Gyazo](https://i.gyazo.com/f49e51fc16d3136feddd40926ca258fe.gif)](https://gyazo.com/f49e51fc16d3136feddd40926ca258fe)

**Comment by Jordaneisenburger** [comment]
@sirugh  after a click don't move your mouse. you'll see the menu stays open.

**Comment by Jordaneisenburger** [comment]
I understand why it stays open technically but that's not the point. What I meant is that on almost every other (non js driven) website the mega menu closes after navigate because the DOM reloads (basically resetting the state). So if for Example the menu isn't just 100px in height but like 500 ish it's hard for users to detect they navigated to another page.

Let's check some other websites for example https://www.amazon.com/ or https://www.walmart.com/ wouldn't it be weird that if you click their menu it would stay open even tho you already navigated.

_In this recording the menu is hard set to replicate a menu with items that would take up 300 px in height_
https://user-images.githubusercontent.com/19858728/111796914-f3336300-88c8-11eb-90b8-28adfd761eea.mov

**Comment by sirugh** [comment]
OK, I think this is good info. Let's see what @schensley says when he gets back from PTO. I think there may be some middle ground where we have the prop I suggested or we detect the amount of items or the height of the menu to auto close :)

**Comment by davemacaulay** [comment]
I agree with you @Jordaneisenburger, I thought this was an interesting UX choice when I started playing with mega menu. Naturally as @sirugh has said we'll defer to @schensley.

**Comment by brendanfalkowski** [comment]
Piling on because it's Friday — the menu should close when you click because the user intends to see content not menu (clicking is intent).

[don't say it, don't say it] ...also the menu shouldn't open on hover because hover isn't intent (clicking is, hover is deciding). I hate seeing hover menus especially if they're mega because it's about as frustrating as anything to avoid tripping. Hover a button to add to cart? Hover to link to follow it? Hover text to highlight it? It's just not natural.

**Comment by sirugh** [comment]
https://css-tricks.com/in-praise-of-the-unambiguous-click-menu/

How serendipitous :) posted the same day we merged mega menu!

**Comment by Jordaneisenburger** [comment]
> Piling on because it's Friday — the menu should close when you click because the user intends to see content not menu (clicking is intent).
> 
> [don't say it, don't say it] ...also the menu shouldn't open on hover because hover isn't intent (clicking is, hover is deciding). I hate seeing hover menus especially if they're mega because it's about as frustrating as anything to avoid tripping. Hover a button to add to cart? Hover to link to follow it? Hover text to highlight it? It's just not natural.

@brendanfalkowski I never thought about it this way, this makes a lot of sense to me lol

**Comment by drpayyne** [comment]
@brendanfalkowski, very interesting take on UX behaviour. 

I'm curious on what you think about hovering over tooltip icons which open a popup showing more information? This is similar to hovering over a category title which opens a popup (just bigger) showing its subcategories, right? Hovering over a category title doesn't navigate to said category as your example of 'hovering over add to cart - adds product to cart' implies so. Navigation happens only on click, not on hover. Thoughts? :)

**Comment by Frodigo** [comment]
Hey,

I am used to navigations that open on hover, and I expect if I click on the navigation link, I will go to dedicated pages. For instance, I click on Tops, and I go to the Tops category page. 

Opening dropdowns on click causes one issue: you cannot go to the dedicated page because click on the link prevents this from opening the submenu.

Anyway, I know that each project can have different requirements.

I agree with @Jordaneisenburger that the mega menu should disappear when you click on the navigation link. 

I would love to add these modifications to the mega menu component: 
1. Mega menu is closing when you navigate to another page
2. Add props/configuration that defines is mega menu work on hover or click. Thanks to that, everyone will be able to decide what solution is better for their project.

Let me know what do you think about that.

Thanks,
Marcin

**Comment by sirugh** [comment]
I think those ideas are good, @Frodigo, but I also think we need to consider the UX for accessing top-level categories. Right now it hovers but you can still navigate to the top-level categories by clicking on them even after the hover is open. If the mega menu only opens on click, how do you access root categories?

**Comment by Jordaneisenburger** [comment]
@sirugh  A solution for the top level click is being given in the post you mentioned right?

**Comment by brendanfalkowski** [comment]
@drpayyne Generally speaking, I haven't built anything hover-first in a long long time because touch devices are never going away. Click-first reaches more people with predictable behavior and doesn't need the overhead of supporting a duplicate affordance in hover, and it frees hover to just helping people understand the element is interactive if they're using a mouse.

Having said that, tooltips are a UI that it's not too crazy to support both affordances because:

1) The trigger area is tiny (not a full width nav bar), so tripping over it is much less common.
2) The expanded area is tiny (not a mega menu), so it's easier to move away from.

It doesn't have the inherent problems of a mega menu being activated by hover, but I would still argue tooltips don't feel wrong in any way being activated by click-only. It's still essentially a button, and buttons don't activate until you press them.

**Comment by sirugh** [comment]
@magento export issue to JIRA project PWA as Story

**Comment by supernova-at** [comment]
Jeremy Charron is going to work on this one.
