### ISSUE TITLE
[bug]: LocaleProvider leads to duplicate query and unnecessary rerender

### ISSUE THREAD

**Issue by larsroettig** [magento/pwa-studio#3693]
**Describe the bug**

**To reproduce**
* Add https://github.com/welldone-software/why-did-you-render
* Create an Empty Page 
* Visit console.log on the new Page
* you get the following messages 
![Screenshot from 2022-02-07 16-59-29](https://user-images.githubusercontent.com/5289370/152824377-8e26738e-5bb7-4980-b5f9-8aa64472cf22.png)

**Expected behaviour**
* No  Error appears 

**Screenshots**

**Possible solutions**

Change:

https://github.com/magento/pwa-studio/blob/03535e58c76c1caad8184cfef1f0f42acd0bf87e/packages/venia-ui/lib/components/App/localeProvider.js#L55-L64

To:
```js
    const handleIntlError = useCallback(error => {
        if (messages) {
            if (error.code === 'MISSING_TRANSLATION') {
                console.warn('Missing translation', error.message);
                return;
            }
            throw error;
        }
    },[messages]);
```

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Magento Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by supernova-at** [comment]
@magento export issue to JIRA project PWA as Bug

**Comment by glo80771** [comment]
The issue is reproducible and hence confirming the issue.

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo80771** [comment]
Hi @larsroettig ,

As per retesting, the issue is not reproducible by following the below steps:

1. Installed the package @welldone-software/why-did-you-render
2. Installed the page craco @craco/craco
3. Created craco.config.js file
4. Created wdyr.js and imported it in index.js
5. Created an empty page 
6. Visited console.log on new page

PFA.
<img width="1422" alt="Screenshot 2023-08-02 at 1 46 22 PM" src="https://github.com/magento/pwa-studio/assets/127736464/a4ec5199-249a-4c25-a15e-41475c1cdae0">

Please let us know if we are missing anything.

**Comment by glo80771** [comment]
Closing the ticket since no response for more than two weeks. Please feel free to reopen the ticket in case the issue is still there.
