### ISSUE TITLE
Place order button not showing when subtotal is zero on checkout 

### ISSUE THREAD

**Issue by arvind-netzwelt** [magento/pwa-studio#4204]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Possible solutions**

Add any ideas about possible solutions to the problem here.

**Debug Report**

Paste the output of `yarn build:report`, and any other context about the problem, here.

**Please complete the following device information:**

-   Device [e.g. iPhone6, PC, Mac, Pixel3]:
-   Browser [e.g. Chrome, Safari]:
-   Browser Version [e.g. 22]:
-   Magento Version [e.g Adobe Commerce 2.4]:

**Please let us know what packages this bug is in regards to:**

-   [ ] `venia-concept`
-   [ ] `venia-ui`
-   [ ] `pwa-buildpack`
-   [ ] `peregrine`
-   [ ] `pwa-devdocs`
-   [ ] `upward-js`
-   [ ] `upward-spec`
-   [ ] `create-pwa`

**Comment by glo80771** [comment]
Hi @arvind-netzwelt ,
Please find below the steps we followed to reproduce.

1. Added the cart price rule with a discount of 100% for both subtotal and shipping charges. PFB the screenshot.
<img width="1010" alt="Screenshot 2023-11-30 at 1 12 53 PM" src="https://github.com/magento/pwa-studio/assets/127736464/d02304d3-0b04-414a-adb8-03cd49d3b154">
2. Added the product to the cart and proceeded to checkout.
3. Reviewed the order and the place order button is enabled.
4. Able to place the order with both signed-in and guest users. PFB the screenshot.
<img width="725" alt="Screenshot 2023-11-30 at 1 15 01 PM" src="https://github.com/magento/pwa-studio/assets/127736464/ea1dba7a-432c-4839-bdef-5af11f13d930">

Hence the issue is not reproducible from our end. Please let us know if we are missing anything.

**Comment by arvind-netzwelt** [comment]
I have implemented the "Zero Subtotal Checkout" payment method

**Comment by glo80771** [comment]
Hi @arvind-netzwelt ,
I have implemented the Zero Subtotal Checkout payment method and added the cart price rule as a 100% discount and still we are not able to reproduce the issue. PFA the video for your reference.

https://github.com/magento/pwa-studio/assets/127736464/1bbb9b00-b8e8-41d1-be4f-c4b7fb56b7d8

Please let us know still we are missing anything.

**Comment by glo82145** [comment]
@adobe export issue to Jira project PWA

**Comment by glo85315** [comment]
Hi @arvind-netzwelt ,  Issue not reproducible. Please reopen if the issue persists .

https://github.com/magento/pwa-studio/assets/159006137/452a3405-24da-42be-a5b8-e90a3c3bbf8a
