### ISSUE TITLE
[bug]: Unable to execute javascript tags which added in block in PWA Venia

### ISSUE THREAD

**Issue by RanjitBShinde** [magento/pwa-studio#4245]
1. Login to Magento Admin
2. Create or Edit block, add html element and add any javascript in that
3. Add that block in footer or somewhere in page
4. Goto PWA Venia frontend and check, javascript is loading but it is not executable.

**Comment by glo85315** [comment]
Hi 
1. Login to Magento Admin
2. Click create page, add html element  Button  and add script tag and inside script add  click button functionality
3. Goto PWA local fronend and check, button is displaying but click button functionality not working , it means script not working
![Uploading Screenshot 2024-04-05 at 11.46.27 AM.png…]()
4. Issue is producible in PWA
<img width="1512" alt="Screenshot 2024-04-05 at 11 46 12 AM" src="https://github.com/magento/pwa-studio/assets/159006137/d11704d7-0b63-4fd0-a1c5-61393a3de0f4">





But 

1. Login to Magento Admin
2. Click create page, add html element  Button  and add script tag and inside script add  click button functionality
3. After create page there is 3 options .delete ,edit, view
5. When we  click view option 
6. Page is open in another window. button is displaying but click button functionality is working fine
7. Issue is not producible in Magento Admin

**Comment by glo85315** [comment]
![Uploading Screenshot 2024-04-05 at 11.46.12 AM.png…]()

**Comment by RanjitBShinde** [comment]
@glo85315 in luma theme it works. Issue is about PWA venia.

**Comment by glo42707** [comment]
@adobe export issue to JIRA project PWA as Bug

**Comment by glo85315** [comment]
Hi @RanjitBShinde , Thank you for reaching out to us regarding the JavaScript execution issue with Magento's PWA Venia storefront. After thorough investigation, we've discovered that React's security measures prevent the execution of JavaScript within static blocks, as it sanitizes HTML content, including script tags.

Unfortunately, due to this limitation within the React framework, we regret to inform you that we won't be able to proceed with your ticket as originally anticipated. We understand the importance of this functionality to you and apologize for any inconvenience this may cause.

If you have any further questions or concerns, please don't hesitate to reach out to us. We're here to help in any way we can.

**Comment by glo82145** [comment]
As we have no update on this ticket for more than 14 days , Hence we are closing this ticket. 
Please feel free to reopen in case of any update.
