### ISSUE TITLE
[FEATURE]: Add to Cart - Sticky Footer for CTAs

### ISSUE THREAD

**Issue by awilcoxa** [magento/pwa-studio#472]
## This issue is for the following packages:

[x ] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ x] Bug
[ ] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

The "Add to Cart" workflow from a product details page is currently implemented as a standalone CTA embedded within the page. The primary CTAs on the PDP should be displayed in a sticky footer, as indicated in the current mockups. 

Additional items from design are defined below. 

## Expected result:

1. PDP calls to action ("Add to Cart") display in sticky footer. Currently, the only CTA is "Add to Cart" as "Buy Now" is deferred for later release. 
2. Single button ("Add to Cart") should display center aligned. 
3. Button style should be as primary (currently implemented as secondary color scheme) 
4. Button states should be added based on mockups (ex: "checkmark" when a product is added to cart)
5. On error (ex. configuration not selected) should scroll to configuration options and display error banner (#783)

## Possible solutions:

**Comment by awilcoxa** [comment]
@soumya-ashok can you add screens?

**Comment by alexandrosk** [comment]
We will need some screens on this one. 
As also we need to take into consideration about the configurable products, with sizes or colors. Should the options be available on the sticky footer aswell?

**Comment by soumya-ashok** [comment]
@alexandrosk - The PD page shows configuration options. If the shopper taps the "Add to Cart" button before selecting product configuration, then the screen scrolls to where the first configuration option begins, with a notification to choose an option.
@awilcoxa I assume the configuration part is out of scope for this issue, since we are just dealing with the sticky footer?

The add to cart sticky footer and interaction is shown in these screens -

![Screen Shot 2018-11-11 at 10.12.41 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/5c829f42-cba7-46ee-aac0-2f30e4717b2a)

**Comment by dmtrkad** [comment]
@soumya-ashok, Could you please provide "operation in Progress" design to cover the loading condtition?What's time interval to show "Ticked button"-state in case to proceed with next selection?

@awilcoxa , @ericerway, Do we need to handle errors and unexpected behavior? What kind of screen or alert messages we need to show ?

Estimation:
1. Sticky footer - 1SP
2. "Add to cart" - ? (Need details to measure an effort)

**Comment by soumya-ashok** [comment]
@dmtrkad The operation in progress would be a button state where the style switches to outline, and there is an indeterminate progress indicator as shown with the 3 dots. I am not sure what you mean by "provide the design". It would not be a static image so I'm not sure what to do here.

The ticked button state would need to remain for 2-3 seconds and then change back to "Add to Cart" - @jimbo does that sound alright to you?

**Comment by awilcoxa** [comment]
adding needs-ux for review from @soumya-ashok need to determine if closing this design gap is high priority based on input from UX/UI

**Comment by soumya-ashok** [comment]
There has been a change to button styles since this issue was last discussed, updated mockups -

![Add to Cart.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/5b71c2a5-4d41-4ce7-a0e6-5152e3e227f5)

Reiterating the interaction detail -
When the shopper taps the add to cart button, provided that all required parameters have been selected, the button switches to the transition state with an indeterminate progress indicator as in mockup.
When the request is successful, the button changes once more to show a check mark. The check mark persists for 5 seconds before changing back to the original "add to cart" state and resets all the selected configuration to their defaults. If the shopper changes the previously selected configuration within 5 seconds, then the button changes back to its original "add to cart" state immediately.

Because add-to-cart is a critical request and also for consistency with similar interactions, it would be good to display a success toast like in the mockup below. However, since it is placed close to the button that also has a state change, I'd like to discuss this before making a decision.

![Add to Cart Success.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/a3922dee-18a3-410b-bd61-f57aecd1586b)

We have also not covered the scenario of what happens when the request is unsuccessful.

**Comment by brendanfalkowski** [comment]
Just an idea — the latency of adding to cart sometimes makes this interaction ***feel*** slow. If you assume adding to cart will succeed 99/100 times (it basically always should when in stock), then it's an opportunity to instantly forward the UI to "added" state. Then finish the actual request invisibly. <1% of the time it fails you need to retread the UI, but overall it's a better experience.

**Comment by soumya-ashok** [comment]
Great recommendation @brendanfalkowski, I'll update the interaction description.

**Comment by soumya-ashok** [comment]
If this has not yet been worked on, we can keep the CTAs on the page (no sticky footer) but place them right under the configuration parameters. This is based on observations during a recent research study. We need some more time to validate if the sticky footer approach is suitable.

![Screen Shot 2019-07-26 at 5.42.54 PM.png](https://images.zenhubusercontent.com/5b89562fba905a6006740695/33334fcf-0425-4d7b-8d2b-79c601ab1bc6)

Except for that detail, all other feedback on interaction etc. is still valid.

**Comment by zetlen** [comment]
This ticket is currently unassigned and @soumya-ashok has helpfully suggested it for Munich Contribution Day 2019. If you want to take this ticket at Munich Contribution day, bear these things in mind:

- This is a major change to the product page UI, so it would be a larger contribution.
- Venia is both an example app, a starter template, and a component library, so its code needs to be clear and consistent. Use existing components where available, and create generic reusable components where possible.
- The "optimistic update" feature described by @brendanfalkowski would be a _huge win_ with a guaranteed Community Engineering award badge! However, this kind of code is hard to write without accidentally repeating yourself a lot throughout the codebase. So make sure that if you write an optimistic update routine, that it's general-purpose enough that it would work for other things besides add to cart (such as updating order or account data, for instance).

**Comment by awilcoxa** [comment]
Closing issue as updated designs no longer call for sticky footer.
