### ISSUE TITLE
Improve Minicart & Checkout Totals

### ISSUE THREAD

**Issue by codeAdrian** [magento/pwa-studio#613]
## This issue is for the following packages:

- [x] `venia-concept`
- [ ] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

## This issue is a:

- [ ] Bug
- [x] Feature suggestion
- [ ] Documentation issue
- [ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             | n/a |
| Operating System + version  | n/a |
| node.js version (`node -v`) | n/a |
| npm version (`npm -v`)      | n/a |

## Description

As a user, I would like to know the grand total and full breakdown of the grand total on final step of the checkout (shipping, tax and any discounts included). Currently, subtotal value is only being displayed which doesn't include that info and may confuse the users when the amount they end up paying differs from the displayed amount.

![screen shot 2018-12-07 at 11 37 51 am](https://user-images.githubusercontent.com/11479290/49643334-b273f080-fa15-11e8-8831-d88ce24d6a33.png)

## Expected result:

This is the result which was implemented in the custom theme. Shipping amount and tax are showing after user has entered shipping method and address on checkout section.

![screen shot 2018-12-07 at 11 47 17 am](https://user-images.githubusercontent.com/11479290/49643391-e0f1cb80-fa15-11e8-8bae-fd621ce2c471.png)

## Possible solutions:

Use total_segments array that contains the full breakdown of the totals.

@ericerway @soumya-ashok let me know what you think. If you agree, I can start working on implementing this improvement right away.

**Comment by awilcoxa** [comment]
@cherdman to check in with Cris

**Comment by codeAdrian** [comment]
@cherdman @awilcoxa I would like to work on this feature if it's free for taking.

**Comment by supernova-at** [comment]
> @cherdman @awilcoxa I would like to work on this feature if it's free for taking.

Hey @codeAdrian it looks like maybe we need some input from @cherdman, @cpartica, and @soumya-ashok before this is ready.

I'm going to un-assign you for now but when the team deems this ready it's all yours.

**Comment by soumya-ashok** [comment]
@supernova-at @awilcoxa This would need us to revisit the current design for checkout. I foresee other changes to the design we have right now based on everything we have learned from research. Would you recommend that we do an interim solution for this based on what we have, or wait until we have more clarity on what the other changes might be and then revise the design?

**Comment by sirugh** [comment]
Of note:

* We are currently using REST for cart/checkout. We can either use REST for this work or we can use GraphQL (if graphql can handle what we need for checkout).

**Comment by sirugh** [comment]
After talking with @awilcoxa we're deciding that this work should probably just wait for the eventual refactor of checkout since that design will include these things anyways. Just to elucidate our options:

a) Use REST
 - requires small refactor such as moving submission of address to before checkout rather than _on_ checkout and re-requesting `/totals` after each step.
 - requires UX/design for display of subtotals/other charges in "v1" venia

b) Use GraphQL
 - requires a large refactor of code
 - should probably wait until we refactor steps to graphql anyways.
 - requires UX/design for display of subtotals/other charges in "v1" venia

Regardless of how we move forward on this we need new UX/design so in my opinion we should just wait for refactor of checkout and wait until we've migrated checkout/cart to graphql.

**Comment by awilcoxa** [comment]
https://jira.corp.magento.com/browse/PWA-184

**Comment by sirugh** [comment]
Now that cart/checkout are being refactored this is unnecessary. Mini-cart display will change eventually, and we can open a ticket at that time for it.
