### ISSUE TITLE
[BUG] Reducing bundle CSS code bloat

### ISSUE THREAD

**Issue by codeAdrian** [magento/pwa-studio#895]
**Describe the bug**
This is something that I have noticed both in venia and in our custom theme. Sometimes we want to create composable classes (for style guide elements like forms, for example). We can use those classes to compose and add additional atrributes, but also we may use them for composition only. Consider the following example https://github.com/magento-research/pwa-studio/blob/release/2.0/packages/venia-concept/src/components/ProductOptions/swatchList.css#L2

This code is valid and the use case is valid. But this code results in the following bloat on the frontend:

<img width="1265" alt="screen shot 2019-02-14 at 8 32 33 am" src="https://user-images.githubusercontent.com/11479290/52770629-e847dd80-3033-11e9-8165-c25a18402f49.png">

<img width="382" alt="screen shot 2019-02-14 at 8 33 02 am" src="https://user-images.githubusercontent.com/11479290/52771185-8ab49080-3035-11e9-9d15-5bab2fb51e7f.png">

Notice the empty `.swatchList-root` class in `<styles>` tag. The unused className and empty style selector produces code bloat. This kind of composition without adding any new attributes may be used often down the line (it's really useful when just concatenating classes), and the resulting code bloat might be significant.

**To Reproduce**
1. Create a className `.test`
2. Compose from another className. For example, `composes: someClassName from /path/to/className.css';`
3. Apply className `.test` to some element. Notice the empty `.test` className in code

**Expected behavior**
Empty CSS classes should be removed from final bundle, but className composition should remain as defined.

**Screenshots**
<img width="1265" alt="screen shot 2019-02-14 at 8 32 33 am" src="https://user-images.githubusercontent.com/11479290/52770629-e847dd80-3033-11e9-8165-c25a18402f49.png">

<img width="382" alt="screen shot 2019-02-14 at 8 33 02 am" src="https://user-images.githubusercontent.com/11479290/52771185-8ab49080-3035-11e9-9d15-5bab2fb51e7f.png">

**Please complete the following device information:**
 - Device: n/a
 - OS: n/a
 - Browser n/a
 - Version n/a
 - Magento Version n/a
 - NPM version n/a
 - Node Version n/a

**Please let us know what packages this bug is in regards to:**
- [x] `venia-concept`
- [x] `pwa-buildpack`
- [ ] `peregrine`
- [ ] `pwa-devdocs`
- [ ] `upward-js`
- [ ] `upward-spec`

**Additional context**

**Possible solutions**
I have tried implementing cssnano to fix this issue, but `composes`runs after cssnano, so cssnano sees the class as non-empty. We might need to consider implementing CSS extraction and apply cssnano optimization after, but maybe community can find a simpler solution. Some related topics on github:

Solution for this issue doesn't apply in newer versions of css-modules: https://github.com/css-modules/css-modules/issues/269

Unresolved issue: https://github.com/css-modules/css-modules/issues/127

**Comment by awilcoxa** [comment]
@jimbo

**Comment by larsroettig** [comment]
@codeAdrian is this still relevant can be closed?

**Comment by jimbo** [comment]
@larsroettig Yes, this issue is still relevant.

It would certainly be nice to find a way to prune empty rulesets during the build. Even without such a solution, though, we should avoid authoring empty rulesets in the first place. A task to solve this issue might involve manually pruning empty rulesets from the codebase—perhaps commenting them out at first.

Another thing highlighted by this issue is that the production build should be emitting much more concise hashes for scoped classnames. As [documented here](https://github.com/webpack-contrib/css-loader#localidentname), our webpack config (specifically, [this line](https://github.com/magento/pwa-studio/blob/develop/packages/pwa-buildpack/lib/WebpackTools/configureWebpack/getModuleRules.js#L108)) should be different in production. Note that neither the module name nor the local name (classname) should be included at all in production—it should be nothing but a brief hash.

**Comment by davemacaulay** [comment]
We deem this as a feature request and are tracking internally under the story: https://jira.corp.magento.com/browse/PWA-176
